[App] Connect novu notifications to UI
SaladTechnologies/salad-applications pull request #1002
Opened 2023-05-16 08:25 UTC by rners01

**Description:** Connect novu notifications to UI
**Notion Task:** https://www.notion.so/App-Connect-Alerts-UI-to-the-real-data-from-Novu-57267998bec6419aaf352d5d64942226
**Notion Project:** https://www.notion.so/saladtech/Frontend-Add-push-notifications-to-the-web-app-3a60520ff8d4485d85965b12fa1c2e84

2023-05-16 09:40 UTC, vitto-moz requested changes

2023-05-16 09:40 UTC, vitto-moz commented on packages/web-app/src/modules/home-views/components/NavigationBar.tsx
> +  return <GardenNovigationBar {...props} notifications={notifications} />
```suggestion
  return <GardenNavigationBar {...props} notifications={notifications} />
```

2023-05-16 09:40 UTC, vitto-moz commented on packages/web-app/src/modules/notifications/utils.tsx
> +}
```suggestion
interface NotificationAction {
  label: string
  onClick: () => void
}
```

2023-05-16 09:40 UTC, vitto-moz commented on packages/web-app/src/modules/notifications/utils.tsx
> +  onDismiss: (notificationID: string) => void,
```suggestion
  onAcknowledge: (notificationId: string) => void,
  onDismiss: (notificationId: string) => void,
```

2023-05-16 09:40 UTC, vitto-moz commented on packages/web-app/src/modules/notifications/models/NotificationMessage.tsx
> +  /** The title. */
we used these 2 ids in widget to distinguish SaladBowl notifications and Novu notifications.
What is the purpose we have them here?

2023-05-16 09:40 UTC, vitto-moz commented on packages/web-app/src/modules/notifications/models/NotificationMessage.tsx
> +  createTime: Date | undefined;
```suggestion
  createDate: Date | undefined;
```

2023-05-16 09:54 UTC, vitto-moz requested changes

2023-05-16 09:54 UTC, vitto-moz commented on packages/web-app/src/modules/home-views/components/NavigationBar.tsx
> +export const NavigationBar: FunctionComponent<NavigationBarProps> = (props) => {
```suggestion
export const NavigationBarWithNotifications: FunctionComponent<NavigationBarProps> = (props) => {
```

2023-05-16 09:54 UTC, vitto-moz commented on packages/web-app/src/modules/home-views/components/NavigationBar.tsx
> +import { NavigationBar as GardenNovigationBar, type NavigationBarProps } from '@saladtechnologies/garden-components'
```suggestion
import { NavigationBar, type NavigationBarProps } from '@saladtechnologies/garden-components'
```

2023-05-16 11:28 UTC, vitto-moz requested changes

2023-05-16 11:28 UTC, vitto-moz commented on packages/web-app/src/modules/notifications/models/NotificationMessage.tsx
> +export interface NovuNotificationAction {
Seems the naming is misleading here
the interface below has nothing common with novu notification template 
```suggestion
export interface NotificationAction {
```

2023-05-16 11:28 UTC, vitto-moz commented on packages/web-app/src/modules/notifications/models/NotificationMessage.tsx
> +export interface NovuNotification {
Seems the naming is misleading here: this interface describes the application needs, but not describe the content of novu notification
```suggestion
export interface Notification {
```

2023-05-16 11:28 UTC, vitto-moz commented on packages/web-app/src/modules/notifications/utils.tsx
> +interface NotificationCta {
```suggestion
interface NovuTemplateCta {
```

2023-05-16 11:28 UTC, vitto-moz commented on packages/web-app/src/modules/notifications/utils.tsx
> +type NotificationCtaContent = NotificationCta['acknowledgeLabel'] | NotificationCta['linkCTA']
```suggestion
type NovuTemplateCtaContent = NotificationCta['acknowledgeLabel'] | NotificationCta['linkCTA']
```

2023-07-25 15:19 UTC, Maks19 requested changes

2023-07-26 11:26 UTC, Maks19 approved these changes

2023-07-26 15:24 UTC, vitto-moz submitted a review, later dismissed

2023-08-28 11:54 UTC, closed without merging