[Web] Redesign earn page balance block
SaladTechnologies/salad-applications pull request #1010
Opened 2023-08-15 11:05 UTC by rners01

**Description:** Redesign earn page balance block
**Notion Task:** https://www.notion.so/saladtech/Redesign-Earn-page-balance-block-6994da3ca35a47c8bb9d2c91ee0bee66?pvs=25
**Notion Project:** https://www.notion.so/saladtech/Frontend-Earning-Page-Design-Refresh-7bc4991e6c5c47168d4450fa257ee9db

<img width="1227" alt="image" src="https://github.com/SaladTechnologies/salad-applications/assets/115642795/f9357717-6624-42ce-a813-b7e1541a00a1">
<img width="619" alt="image" src="https://github.com/SaladTechnologies/salad-applications/assets/115642795/86de6885-466b-4053-b0f9-ba23dd4d1dd2">

2023-08-15 11:07 UTC, rners01 commented on packages/web-app/src/modules/earn-views/components/BalanceStat.tsx
> +    color: '#D5DADF',
tbd with Nelson

2023-08-15 15:39 UTC, Maks19 requested changes

2023-08-15 15:39 UTC, Maks19 commented on packages/web-app/src/modules/earn-views/components/EarningSummary.tsx
> +      <div className={classes.title}>Earning Summary</div>
Let's use `SectionHeader` here

2023-08-15 15:39 UTC, Maks19 commented on packages/web-app/src/modules/earn-views/pages/EarningSummaryPage.tsx
> +export const EarningSummaryPage = withLogin(withStyles(styles)(EarningSummaryPageRaw), EarningInformationPage)
Why did you change it?

2023-08-15 15:39 UTC, Maks19 commented on packages/web-app/src/modules/earn-views/components/EarningSummary.tsx
> +        <BalanceStat title={'Current Balance'} value={formatBalance(currentBalance)} />
You don't need {} in `title`

2023-08-15 15:39 UTC, Maks19 commented on packages/web-app/src/modules/earn-views/components/EarningSummary.tsx
> +    return `${count} rewards`
Can `count` be 0?

2023-08-15 15:39 UTC, Maks19 commented on packages/web-app/src/modules/earn-views/EarningSummaryContainer.tsx
> +  totalChoppingHours: store.xp.currentXp && getNumberWithCommas((store.xp.currentXp / 60).toFixed(0)),
Let's move it to the variable. You can use conditional there and put 0 if `!store.xp.currentXp`

2023-08-15 16:01 UTC, rners01 commented on packages/web-app/src/modules/earn-views/components/EarningSummary.tsx
> +    return `${count} rewards`
yes

2023-08-16 09:09 UTC, rners01 commented on packages/web-app/src/modules/earn-views/components/EarningSummary.tsx
> +      <div className={classes.title}>Earning Summary</div>
it has totally different styles

2023-08-16 09:10 UTC, rners01 commented on packages/web-app/src/modules/earn-views/pages/EarningSummaryPage.tsx
> +export const EarningSummaryPage = withLogin(withStyles(styles)(EarningSummaryPageRaw), EarningInformationPage)
I changed it from class component to fucntional

2023-08-16 09:11 UTC, rners01 commented on packages/web-app/src/modules/earn-views/components/EarningSummary.tsx
> +    return `${count} rewards`
yes

2023-08-16 09:11 UTC, rners01 commented on packages/web-app/src/modules/earn-views/EarningSummaryContainer.tsx
> +  totalChoppingHours: store.xp.currentXp && getNumberWithCommas((store.xp.currentXp / 60).toFixed(0)),
What is the pros to move it to  the variable?

2023-08-16 09:21 UTC, Maks19 commented on packages/web-app/src/modules/earn-views/components/EarningSummary.tsx
> +      <div className={classes.title}>Earning Summary</div>
It looks pretty much the same for all headers

<img width="753" alt="image" src="https://github.com/SaladTechnologies/salad-applications/assets/41080668/9e7887ff-21a0-4b02-b89b-be49b3fb1714">

2023-08-16 09:21 UTC, Maks19 commented on packages/web-app/src/modules/earn-views/pages/EarningSummaryPage.tsx
> +export const EarningSummaryPage = withLogin(withStyles(styles)(EarningSummaryPageRaw), EarningInformationPage)
Yes, the naming
Why did you change the pattern with naming using an underscore?

2023-08-16 09:23 UTC, Maks19 commented on packages/web-app/src/modules/earn-views/EarningSummaryContainer.tsx
> +  totalChoppingHours: store.xp.currentXp && getNumberWithCommas((store.xp.currentXp / 60).toFixed(0)),
I believe it should be clear for understanding. And you'll be able to put 0 in conditional to not check on undefined `totalChoppingHours`

2023-08-23 08:58 UTC, closed without merging

2023-08-23 08:58 UTC, Maks19 commented
Closed as all changes in new PR - https://github.com/SaladTechnologies/salad-applications/pull/1012