[Web-App] Redesign earn page
SaladTechnologies/salad-applications pull request #1012
Opened 2023-08-21 13:22 UTC by Maks19

**Description:** Redesign earn page

**Notion Project:** https://www.notion.so/saladtech/Frontend-Earning-Page-Design-Refresh-7bc4991e6c5c47168d4450fa257ee9db

2023-08-22 11:15 UTC, vitto-moz requested changes

2023-08-22 11:15 UTC, vitto-moz commented on packages/web-app/src/modules/earn-views/components/EarningChart.tsx
> +    fontFamily: 'Mallory',
wonder why we have to set the `fontFamily` for a particular class, when we have it set globally as `Mallory`

2023-08-22 11:15 UTC, vitto-moz commented on packages/web-app/src/modules/earn-views/components/EarningChart.tsx
> +    : moment(payload.value).add(15, 'minute').format('D')
nested ternary is a bad practice - as decreases readability

2023-08-22 11:15 UTC, vitto-moz commented on packages/web-app/src/modules/earn-views/components/LatestRewardsRedeemed/components/LatestRewardsRedeemedCard.tsx
> +}
why don't we just use `RedeemedReward` type here?

2023-08-22 11:15 UTC, vitto-moz commented on packages/web-app/src/modules/vault/VaultStore.tsx
> +  public latestCompletedRedeemedRewards: Map<string, RedeemedReward> = new Map<string, RedeemedReward>()
what is the idea of using `Map` here?

2023-08-22 11:15 UTC, vitto-moz commented on packages/web-app/src/modules/vault/VaultStore.tsx
> +    } catch {}
any error handling here?

2023-08-22 11:15 UTC, vitto-moz commented on packages/web-app/src/modules/vault/VaultStore.tsx
> +    } catch {}
any error handling here?

2023-08-22 16:10 UTC, Maks19 commented on packages/web-app/src/modules/earn-views/components/EarningChart.tsx
> +    fontFamily: 'Mallory',
we're styling elements from third party library so we need `fontFamily` here

2023-08-22 16:27 UTC, Maks19 commented on packages/web-app/src/modules/vault/VaultStore.tsx
> +    } catch {}
Added console error as we do not need to interrupt other logic or show any error screen

2023-08-22 16:27 UTC, Maks19 commented on packages/web-app/src/modules/earn-views/components/LatestRewardsRedeemed/components/LatestRewardsRedeemedCard.tsx
> +}
Fixed

2023-08-22 16:27 UTC, Maks19 commented on packages/web-app/src/modules/earn-views/components/EarningChart.tsx
> +    : moment(payload.value).add(15, 'minute').format('D')
Agreed
Changed

2023-08-22 16:27 UTC, Maks19 commented on packages/web-app/src/modules/balance/utils.tsx
> +    item.reduce((acc, curr) => ({
Days
Changed to `day`

2023-08-25 12:41 UTC, Maks19 commented on packages/web-app/package.json
Update garden-components version when the build is fixed and this [PR ](https://github.com/SaladTechnologies/salad-applications/pull/1002) will be merged

2023-09-06 09:17 UTC, Maks19 commented
Open new PR with fixed build https://github.com/SaladTechnologies/salad-applications/pull/1022

2023-09-06 09:17 UTC, closed without merging