[Web-App] Remove supertokens
SaladTechnologies/salad-applications pull request #1039
Opened 2023-09-20 14:42 UTC by Maks19

**Description:** Remove supertokens

**Notion Task:** https://www.notion.so/saladtech/Web-App-remove-SuperTokens-2992c392035c405194b6e56cb527ba19

2023-09-21 09:44 UTC, vitto-moz commented on packages/web-app/src/axiosFactory.tsx
> +    withCredentials: true,
is this for third-party requests? 
do we use axios to request third-party services?

2023-09-21 09:46 UTC, Maks19 commented on packages/web-app/src/axiosFactory.tsx
> +    withCredentials: true,
It was done for requests should be made using credentials such as cookies, authorization headers or TLS client certificates
Without this parameter, our axios requests won't include `auth` token

2023-09-21 14:00 UTC, seniorquico commented on packages/web-app/src/axiosFactory.tsx
> +    withCredentials: true,
Is this httpClient used to make requests to any API other than ours? If yes, then ideally this value is set true only for those requests.

2023-09-21 14:02 UTC, seniorquico requested changes

2023-09-21 14:02 UTC, seniorquico commented on packages/web-app/src/axiosFactory.tsx
> +          store.auth.setIsAuthenticated(false)
Is the httpClient this interceptor attached to used to make requests to any API other than ours? If yes, then a failing request to another API will cause the app to logout. The removed SuperTokens session check first verified that it was actually expired before causing the app to logout.

2023-09-21 14:26 UTC, Maks19 commented on packages/web-app/src/axiosFactory.tsx
> +    withCredentials: true,
We're not making any third-party requests with an axios and the `httpClient` is axios instance so it's not making requests to any API other than ours

2023-09-21 14:29 UTC, Maks19 commented on packages/web-app/src/axiosFactory.tsx
> +          store.auth.setIsAuthenticated(false)
We're not making any third-party requests with an axios so this interceptor is not attached to requests to any API other than ours

2023-09-21 14:47 UTC, seniorquico approved these changes

2023-09-22 14:15 UTC, vitto-moz approved these changes

2023-09-22 14:41 UTC, merged