[WebApp] Add Profile page google sso linking
SaladTechnologies/salad-applications pull request #1085
Opened 2023-11-13 16:23 UTC by rners01

**Description:** Add Profile page google sso linking
**Project:** https://www.notion.so/Frontend-Google-SSO-Account-Connections-38e4c91aaf184133a71187ce594e3994

<img width="996" alt="image" src="https://github.com/SaladTechnologies/salad-applications/assets/115642795/3261e6ab-9315-4026-882e-826591610758">
<img width="996" alt="image" src="https://github.com/SaladTechnologies/salad-applications/assets/115642795/61cd27de-50f7-4ff5-a047-140d922e12e1">
<img width="996" alt="image" src="https://github.com/SaladTechnologies/salad-applications/assets/115642795/aafee23f-a1cd-4514-a452-aac2d3a28644">
<img width="996" alt="image" src="https://github.com/SaladTechnologies/salad-applications/assets/115642795/1e3567ab-9625-4707-b1ab-e73975232a2f">
<img width="996" alt="image" src="https://github.com/SaladTechnologies/salad-applications/assets/115642795/e8b05125-0f81-49dc-a23e-bb239c9f1ffa">

2023-11-16 14:25 UTC, vitto-moz requested changes

2023-11-16 14:43 UTC, Maks19 requested changes

2023-11-16 14:43 UTC, Maks19 commented on packages/web-app/src/modules/profile/ProfileStore.tsx
> +        return this.store.auth.successfulExternalProviderConnection()
Why do you need `return`?

2023-11-16 14:43 UTC, Maks19 commented on packages/web-app/src/modules/profile/ProfileStore.tsx
> +        return this.store.auth.failedExternalProviderConnection()
Why do you need `return`?

2023-11-16 14:43 UTC, Maks19 commented on packages/web-app/src/modules/profile/ProfileStore.tsx
> +      if (authProviderConnections.data && authProviderConnections.data.length > 0) {
```suggestion
      if (authProviderConnections.data?.length > 0) {
```

2023-11-16 14:43 UTC, Maks19 commented on packages/web-app/src/modules/account-views/account-views/components/Account.tsx
> +  connectedGoogleAccountEmail: string
```suggestion
  connectedGoogleAccountEmail?: string
```

2023-11-16 14:43 UTC, Maks19 commented on packages/web-app/src/modules/account-views/account-views/components/GoogleSignInForm.tsx
> +  const shouldEnableGoogleSignInButton = !isTermsAndConditionsRequired || isTermsAndConditionsAccepted
Do we have conditional when `TermsAndConditions` **is not** required and **is not** accepted?

2023-11-16 15:08 UTC, rners01 commented on packages/web-app/src/modules/profile/ProfileStore.tsx
> +        return this.store.auth.successfulExternalProviderConnection()
to stop further execution if there is any

2023-11-16 15:09 UTC, rners01 commented on packages/web-app/src/modules/profile/ProfileStore.tsx
> +        return this.store.auth.successfulExternalProviderConnection()
I suppose before that there was some code under but now its not required

2023-11-16 17:26 UTC, rners01 commented on packages/web-app/src/modules/account-views/account-views/components/Account.tsx
> +    paddingBottom: 40,
yes, changed to the `number` variant

2023-11-16 17:26 UTC, rners01 commented on packages/web-app/src/modules/profile/ProfileStore.tsx
> +        return this.store.auth.failedExternalProviderConnection()
removed

2023-11-16 17:26 UTC, rners01 commented on packages/web-app/src/modules/profile/ProfileStore.tsx
> +        return this.store.auth.successfulExternalProviderConnection()
removed

2023-11-17 15:50 UTC, vitto-moz approved these changes

2023-11-17 15:57 UTC, Maks19 submitted a review, later dismissed

2023-11-20 16:29 UTC, Maks19 approved these changes

2023-11-21 10:16 UTC, merged