[WebApp] Add static earn page for guest users
SaladTechnologies/salad-applications pull request #1101
Opened 2023-12-15 12:16 UTC by rners01

https://www.notion.so/saladtech/Frontend-Kitchen-Website-Navigation-1b44b7c416e74f4db46cade6c21a6456

<img width="1278" alt="image" src="https://github.com/SaladTechnologies/salad-applications/assets/115642795/feef64ec-f255-4999-8940-a512877b0102">
<img width="1278" alt="image" src="https://github.com/SaladTechnologies/salad-applications/assets/115642795/cff73cd3-5d08-4e93-854f-3f4445076493">

2023-12-15 13:30 UTC, Maks19 requested changes

2023-12-15 13:32 UTC, rners01 commented on packages/web-app/src/modules/earn-views/pages/EarnInfoPage.tsx
> +    minWidth: 64,
what do you mean?

2023-12-15 13:33 UTC, rners01 commented on packages/web-app/src/modules/earn-views/pages/EarnInfoPage.tsx
> +    minWidth: 64,
Im following one approach without px

2023-12-15 13:34 UTC, rners01 commented on packages/web-app/src/modules/earn-views/pages/EarnInfoPage.tsx
> +            <p className={classes.descriptiom}>
no, it has different styles

2023-12-15 13:35 UTC, rners01 commented on packages/web-app/src/modules/earn-views/pages/EarnInfoPage.tsx
> +            <p className={classes.downloadDescriptiom}>
-//- 
https://github.com/SaladTechnologies/salad-applications/pull/1101#discussion_r1427981547

2023-12-15 13:35 UTC, rners01 commented on packages/web-app/src/modules/earn-views/pages/EarnInfoPage.tsx
> +              <a
why we need this change here

2023-12-15 13:36 UTC, rners01 commented on packages/web-app/src/modules/earn-views/pages/EarnInfoPage.tsx
> +const earnTypes = [
I was thinking to create separate contsnsts file but decided to keep it here as there'r not much code and keep it closer to the render

2023-12-15 13:37 UTC, rners01 commented on packages/web-app/src/modules/earn-views/pages/EarnInfoPage.tsx
> +const styles = (theme: SaladTheme) => ({
it would break some code usage like using values without `px` and media queries

2023-12-15 14:30 UTC, Maks19 commented on packages/web-app/src/modules/earn-views/pages/EarnInfoPage.tsx
> +    minWidth: 64,
But you have `gap` with string value

2023-12-15 14:30 UTC, Maks19 commented on packages/web-app/src/modules/earn-views/pages/EarnInfoPage.tsx
> +const earnTypes = [
Why do we need to keep closer to the render?

2023-12-15 14:33 UTC, Maks19 commented on packages/web-app/src/modules/earn-views/pages/EarnInfoPage.tsx
> +            <p className={classes.descriptiom}>
`baseM` has the same font size and I think it good approach to inherent created font styles and to not use different each time

2023-12-15 14:34 UTC, Maks19 commented on packages/web-app/src/modules/earn-views/pages/EarnInfoPage.tsx
> +            <p className={classes.downloadDescriptiom}>
same font size (`baseM`)

2023-12-15 14:34 UTC, Maks19 commented on packages/web-app/src/modules/earn-views/pages/EarnInfoPage.tsx
> +              <a
It's good approach to use already created components for links

2023-12-15 14:38 UTC, Maks19 commented on packages/web-app/src/modules/earn-views/pages/EarnInfoPage.tsx
> +            <a href="/download" className={classes.downloadButtonLink}>
But how we're redirecting there if it lives in the different environment

2023-12-15 22:40 UTC, rners01 commented on packages/web-app/src/modules/earn-views/pages/EarnInfoPage.tsx
> +            <p className={classes.descriptiom}>
no different line height

2023-12-15 22:40 UTC, rners01 commented on packages/web-app/src/modules/earn-views/pages/EarnInfoPage.tsx
> +    minWidth: 64,
gap wouldnt work for me without px

2023-12-15 22:41 UTC, rners01 commented on packages/web-app/src/modules/earn-views/pages/EarnInfoPage.tsx
> +            <a href="/download" className={classes.downloadButtonLink}>
it redirects with page reload

2023-12-15 22:41 UTC, rners01 commented on packages/web-app/src/modules/earn-views/pages/EarnInfoPage.tsx
> +              <a
what do you mean by already created?

2023-12-15 22:42 UTC, rners01 commented on packages/web-app/src/modules/earn-views/pages/EarnInfoPage.tsx
> +              <a
the Link from react router were created for specific purposes

2023-12-15 22:42 UTC, rners01 commented on packages/web-app/src/modules/earn-views/pages/EarnInfoPage.tsx
> +              <a
I don't see why here we need to use it over simple <a href link

2023-12-15 22:43 UTC, rners01 commented on packages/web-app/src/modules/earn-views/pages/EarnInfoPage.tsx
> +const earnTypes = [
is there any constraints here to keep it like that?

2023-12-18 15:01 UTC, Maks19 approved these changes

2023-12-18 18:12 UTC, merged