[WebApp] Skip star chef notifications
SaladTechnologies/salad-applications pull request #1123
Opened 2024-02-23 13:38 UTC by Maks19

**Description:** Skip star chef notifications

**Issue:** https://www.notion.so/saladtech/Web-App-Skip-Star-Chef-notifications-avoid-set-read-status-for-91ba17686d4f49d5adb9460fd6e738bb

2024-02-23 14:01 UTC, vitto-moz requested changes

2024-02-23 14:01 UTC, vitto-moz commented on packages/web-app/src/modules/home-views/components/NavigationBarWithNovuNotifications.tsx
> +    (messageId: IMessageId, seen: boolean, read: boolean) => {
as we pass array, let's use plural form probably?

```suggestion
    (messageIds: IMessageId, seen: boolean, read: boolean) => {
```

2024-02-23 14:03 UTC, Maks19 commented on packages/web-app/src/modules/home-views/components/NavigationBarWithNovuNotifications.tsx
> +  const { markNotificationsAs } = useMarkNotificationsAs()
It's using in useEffect

2024-02-23 14:03 UTC, Maks19 commented on packages/web-app/src/modules/home-views/components/NavigationBarWithNovuNotifications.tsx
> +    (messageId: IMessageId, seen: boolean, read: boolean) => {
It's can be not an array

2024-02-23 14:04 UTC, Maks19 commented on packages/web-app/src/modules/home-views/components/NavigationBarWithNovuNotifications.tsx
> +  const hasUnseenNotifications = !!(unseenNotificationsIds && unseenNotificationsIds?.length > 0)
We're not expecting undefined here

2024-02-23 14:07 UTC, Maks19 commented on packages/web-app/src/modules/home-views/components/NavigationBarWithNovuNotifications.tsx
> +  )
I would prefer to stay with `filteredUnreadNovuNotifications `
It can be filtered with another conditional

2024-02-23 14:07 UTC, Maks19 commented on packages/web-app/src/modules/home-views/components/NavigationBarWithNovuNotifications.tsx
> +    .map((unseenNovuNotification) => unseenNovuNotification._id)
Agree fixed

2024-02-23 16:51 UTC, vitto-moz commented on packages/web-app/src/modules/home-views/components/NavigationBarWithNovuNotifications.tsx
> +  )
but it's not right now... we can change the name when conditions changed

2024-02-23 16:52 UTC, vitto-moz commented on packages/web-app/src/modules/home-views/components/NavigationBarWithNovuNotifications.tsx
> +  const hasUnseenNotifications = !!(unseenNotificationsIds && unseenNotificationsIds?.length > 0)
didn't get. Won't the suggested line work?

2024-02-23 16:53 UTC, Maks19 commented on packages/web-app/src/modules/home-views/components/NavigationBarWithNovuNotifications.tsx
> +  const hasUnseenNotifications = !!(unseenNotificationsIds && unseenNotificationsIds?.length > 0)
Nope

2024-02-23 16:54 UTC, Maks19 commented on packages/web-app/src/modules/home-views/components/NavigationBarWithNovuNotifications.tsx
> +  )
Okay 
Fixed

2024-02-23 16:55 UTC, vitto-moz commented on packages/web-app/src/modules/home-views/components/NavigationBarWithNovuNotifications.tsx
> +  const { markNotificationsAs } = useMarkNotificationsAs()
yeah, that's why I refine if `markNotificationsAs ` is memoized, because if not, the `useCallback` returns new function every time

2024-02-23 16:56 UTC, vitto-moz commented on packages/web-app/src/modules/home-views/components/NavigationBarWithNovuNotifications.tsx
> +    (messageId: IMessageId, seen: boolean, read: boolean) => {
we passing array and it's confusing: the only one id as parameter but we pass an array. 
I know it's novu stuff, but we can make things more clear on our side

2024-02-26 14:33 UTC, vitto-moz approved these changes

2024-02-26 15:22 UTC, merged