[Web-app] Fix notifications repeated mark as read requests
SaladTechnologies/salad-applications pull request #1137
Opened 2024-04-15 12:04 UTC by rners01

Fix notifications repeated mark as read requests, when we open drawer with unseen notifications

![image](https://github.com/SaladTechnologies/salad-applications/assets/115642795/57aa67b7-a0b3-4f5b-b45c-0b0e540c9489)

2024-04-15 14:43 UTC, vitto-moz requested changes

2024-04-15 14:43 UTC, vitto-moz commented on packages/web-app/src/modules/home-views/components/NavigationBarWithNovuNotifications.tsx
> +  }, [isNotificationsDrawerOpened, handleMarkNotificationAs, hasUnseenNotifications])
Skip dependency can potentially lead to the malfunctions. Let's try to resolve with caching `useMemo`: 

```
  const unreadNovuNotificationsWithoutStarChef = useMemo(() => {
    return unreadNovuNotifications?.filter((unreadNovuNotification) => !unreadNovuNotification.payload?.starChefStatus)
  }, [unreadNovuNotifications])

  const unseenNovuNotificationsIds = useMemo(() => {
    return unreadNovuNotificationsWithoutStarChef
      ?.filter((unreadNovuNotificationWithoutStarChef) => !unreadNovuNotificationWithoutStarChef.seen)
      .map((unseenNovuNotification) => unseenNovuNotification._id)
  }, [unreadNovuNotificationsWithoutStarChef])

  const hasUnseenNotifications = !!unseenNovuNotificationsIds?.length

 ....................
 ...........

  useEffect(() => {
    if (isNotificationsDrawerOpened && hasUnseenNotifications) {
      handleMarkNotificationAs(unseenNovuNotificationsIds, true, false)
    }
  }, [isNotificationsDrawerOpened, handleMarkNotificationAs, hasUnseenNotifications, unseenNovuNotificationsIds])

2024-04-16 05:56 UTC, rners01 commented on packages/web-app/src/modules/home-views/components/NavigationBarWithNovuNotifications.tsx
> +  }, [isNotificationsDrawerOpened, handleMarkNotificationAs, hasUnseenNotifications])
agree

2024-04-16 10:01 UTC, Maks19 approved these changes

2024-04-16 11:16 UTC, vitto-moz approved these changes

2024-04-16 11:34 UTC, merged