[WebApp] Create earning line chart
SaladTechnologies/salad-applications pull request #1149
Opened 2024-06-19 14:21 UTC by Maks19

**Description:** Create earning line chart

**Issue:** https://www.notion.so/saladtech/Create-new-line-chart-for-multiple-IDs-5219629c3455462fb62f081f7e844d29

2024-06-20 11:20 UTC, vitto-moz commented on packages/web-app/src/modules/earn-views/EarningLineChartContainer.tsx
> +  const earningsPerMachine24hours = {
this type is not aligned with the one we have fetched with Kiota 
```

2024-06-20 17:04 UTC, vitto-moz requested changes

2024-06-20 17:04 UTC, vitto-moz commented on packages/web-app/src/modules/earn-views/components/EarningChart.tsx
>  interface CustomTick extends WithStyles<typeof styles> {
```suggestion
interface CustomizedXAxisTickProps extends WithStyles<typeof styles> {
```

2024-06-20 17:04 UTC, vitto-moz commented on packages/web-app/src/modules/earn-views/components/EarningLineChart.tsx
> +}
looks like we don't pass something except of `is24HoursChart` in this component: do we still need all other properties? 

`<CustomizedXAxisTick is24HoursChart={is24HoursChart} />`

2024-06-20 17:04 UTC, vitto-moz commented on packages/web-app/src/modules/earn-views/components/EarningLineChart.tsx
> +  const shouldShowAmPm = payload.value === '00' || payload.value === '12'
Can we replace '00' and '12' with some meaningful constants?

2024-06-20 17:14 UTC, Maks19 commented on packages/web-app/src/modules/earn-views/components/EarningLineChart.tsx
> +}
It's passed from XAxis and I use these props inside CustomizedXAxisTick

2024-06-20 17:14 UTC, Maks19 commented on packages/web-app/src/modules/earn-views/components/EarningLineChart.tsx
> +const _EarningLineChart = ({ classes, earningsPerMachine, daysShowing }: Props) => {
I believe it's comment duplication 
Moved CustomizedXAxisTick  to it's own file

2024-06-20 17:21 UTC, Maks19 commented on packages/web-app/src/modules/earn-views/components/EarningLineChart.tsx
> +  const shouldShowAmPm = payload.value === '00' || payload.value === '12'
Done

2024-06-20 17:21 UTC, Maks19 commented on packages/web-app/src/modules/earn-views/components/EarningLineChart.tsx
> +const CustomizedXAxisTick = (props: CustomTick) => {
Done

2024-06-20 17:21 UTC, Maks19 commented on packages/web-app/src/modules/earn-views/components/EarningLineChart.tsx
> +const styles = (theme: SaladTheme) => ({
Done

2024-06-20 17:26 UTC, Maks19 commented on packages/web-app/src/modules/earn-views/components/EarningChart.tsx
>  interface CustomTick extends WithStyles<typeof styles> {
Let's refactor EarningChart.tsx in another PR

2024-06-21 12:41 UTC, vitto-moz approved these changes

2024-06-21 12:53 UTC, merged