[WebApp] Add passkey error handling
SaladTechnologies/salad-applications pull request #1172
Opened 2024-08-09 13:02 UTC by vitto-moz

https://www.notion.so/saladtech/FE-Add-Passkey-error-handling-125d35393a7a4f9787e1bbe8bfa07bad?pvs=4

2024-08-12 17:46 UTC, Maks19 requested changes

2024-08-12 17:46 UTC, Maks19 commented on packages/web-app/src/modules/passkey-setup/components/PasskeySetupPage.tsx
> +                                errorText={errorText}
Can you add background to error text?
Red text on green background looks not so good
![image](https://github.com/user-attachments/assets/578571a9-8d77-4ca0-8b10-93d51e04cc79)

2024-08-12 18:40 UTC, vitto-moz commented on packages/web-app/src/modules/passkey-setup/components/PasskeySetupPage.tsx
> +                            const addPasskeyFailedErrorText = hasRegisterPasskeyFailed && addPasskeyFailedText
`addPasskeyFailedText` is constant 


const addPasskeyFailedText = 'There was an error setting up your passkey. Try again.'

2024-08-12 18:41 UTC, vitto-moz commented on packages/web-app/src/modules/passkey-setup/components/PasskeySetupPage.tsx
> +                      <form onSubmit={handleSubmit} className={classes.formWrapper} onChange={handlePasskeyNameChange}>
Why? User should have another chance to try

2024-08-12 18:53 UTC, vitto-moz commented on packages/web-app/src/modules/passkey-setup/components/PasskeySetupPage.tsx
> +                                errorText={errorText}
Added 
![image](https://github.com/user-attachments/assets/1b76c62b-08c2-4743-a7dc-c9af04039cdb)

2024-08-13 09:17 UTC, Maks19 commented on packages/web-app/src/modules/passkey-setup/components/PasskeySetupPage.tsx
> +                            const addPasskeyFailedErrorText = hasRegisterPasskeyFailed && addPasskeyFailedText
So why do you need to check it in addPasskeyFailedErrorText ?
`const addPasskeyFailedErrorText = hasRegisterPasskeyFailed && addPasskeyFailedText`

2024-08-13 09:19 UTC, Maks19 commented on packages/web-app/src/modules/passkey-setup/components/PasskeySetupPage.tsx
> +                      <form onSubmit={handleSubmit} className={classes.formWrapper} onChange={handlePasskeyNameChange}>
It would unblock when error disappear. Same as you did with input. What do you think about it?

2024-08-13 09:25 UTC, Maks19 commented on packages/web-app/src/modules/passkey-setup/components/PasskeySetupPage.tsx
> +                            const addPasskeyFailedErrorText = hasRegisterPasskeyFailed && addPasskeyFailedText
In `addPasskeyFailedErrorText` you'll have text (There was an error setting up your passkey. Try again.') or false value. Is it expected?

2024-08-13 09:27 UTC, vitto-moz commented on packages/web-app/src/modules/passkey-setup/components/PasskeySetupPage.tsx
> +                            const addPasskeyFailedErrorText = hasRegisterPasskeyFailed && addPasskeyFailedText
here is the entire logic of error displaying logic 
we make a check you mentioned above to set false for `addPasskeyFailedErrorText ` if `hasRegisterPasskeyFailed` is `false`
```
 const validationErrorText =  meta.error && meta.touched && (meta.error ?? addPasskeyFailedText)
 const addPasskeyFailedErrorText = hasRegisterPasskeyFailed && addPasskeyFailedText
 const errorText = validationErrorText ?? addPasskeyFailedErrorText

2024-08-13 09:34 UTC, vitto-moz commented on packages/web-app/src/modules/passkey-setup/components/PasskeySetupPage.tsx
> +                      <form onSubmit={handleSubmit} className={classes.formWrapper} onChange={handlePasskeyNameChange}>
I think blocked "Add Passkey" button would be confusing UX. 
For example: 

1. user entered the passkey name
2. the "Add Passkey" button is available and user has it clicked
3. Password Manager dialog has started
4. user accidentally clicked "Cancel" button 
5. The Password Manager dialog has disappeared and the error message appeared below the input "'There was an error setting up your passkey. Try again.'"
6. User is trying to click "Add Passkey" button again, but it's disabled ....

2024-08-13 09:42 UTC, Maks19 commented on packages/web-app/src/modules/passkey-setup/components/PasskeySetupPage.tsx
> +                            const addPasskeyFailedErrorText = hasRegisterPasskeyFailed && addPasskeyFailedText
```suggestion
                            const validationErrorText = meta.error && meta.touched ? meta.error : null
                            const addPasskeyFailedErrorText = hasRegisterPasskeyFailed ? addPasskeyFailedText : null
```

2024-08-13 10:13 UTC, Maks19 approved these changes

2024-08-13 10:14 UTC, merged