[WebApp] Add passkey delete confirmation screen
SaladTechnologies/salad-applications pull request #1173
Opened 2024-08-12 10:30 UTC by Maks19

**Description:** Add passkey delete confirmation screen

**Issue:** https://www.notion.so/saladtech/FE-Delete-Passkey-Confirmation-UI-e8c8ef4fff424d458fec25d1e348a604

![image](https://github.com/user-attachments/assets/4530d84a-0a69-44de-9cc9-8adea72f513e)
![image](https://github.com/user-attachments/assets/0719c1f0-3be7-4196-9423-86bdd5ee439d)

2024-08-12 16:20 UTC, vitto-moz requested changes

2024-08-12 16:20 UTC, vitto-moz commented on packages/web-app/src/modules/passkey-delete/PasskeyDeletePageContainer.tsx
> +    isLastPasskey: store.passkey.passkeys.length < 2,
```suggestion
    isLastPasskey: store.passkey.passkeys.length === 1
```

2024-08-12 16:20 UTC, vitto-moz commented on packages/web-app/src/modules/passkey-delete/PasskeyDeletePageContainer.tsx
> +  }
``mapStoreToProps` is for mapping only, there should not be any other functionality

2024-08-12 16:20 UTC, vitto-moz commented on packages/web-app/src/modules/passkey-delete/PasskeyDeletePageContainer.tsx
> +    passkeyNickname: passkeyNickname,
```suggestion
    passkeyNickname,
```

2024-08-13 09:56 UTC, vitto-moz requested changes

2024-08-13 09:56 UTC, vitto-moz commented on packages/web-app/src/modules/passkey-delete/PasskeyDeletePageContainer.tsx
> +  const isLastPasskey = store.passkey.passkeys.length === 2
didn't get a logic 
when there are 2 passkeys, why the passkey is last?

2024-08-13 09:56 UTC, vitto-moz commented on packages/web-app/src/modules/passkey-delete/PasskeyDeletePageContainer.tsx
> +  const isPasskeyExisting = store.passkey.passkeys.some((passkey) => passkey.id === passkeyId)
```suggestion
  const passkey= store.passkey.passkeys.find((passkey) => passkey.id === passkeyId)
  const passkeyNickname = passkey?.displayName
  const isPasskeyExisting = !!passkey
```

2024-08-13 09:56 UTC, vitto-moz commented on packages/web-app/src/modules/passkey-delete/PasskeyDeletePageContainer.tsx
> +    passkeyNickname,
you can just pass `passkey` instead of 
`isPasskeyExisting` and `passkeyNickname`
and make other mapping inside the component

2024-08-13 10:03 UTC, Maks19 commented on packages/web-app/src/modules/passkey-delete/PasskeyDeletePageContainer.tsx
> +  const isPasskeyExisting = store.passkey.passkeys.some((passkey) => passkey.id === passkeyId)
Fixed

2024-08-13 10:03 UTC, Maks19 commented on packages/web-app/src/modules/passkey-delete/PasskeyDeletePageContainer.tsx
> +  const isLastPasskey = store.passkey.passkeys.length === 2
It should be 1 here.
Changed it

2024-08-13 10:14 UTC, vitto-moz approved these changes

2024-08-13 10:20 UTC, merged