[WebApp] Add protected action page
SaladTechnologies/salad-applications pull request #1183
Opened 2024-08-20 13:44 UTC by Maks19

**Description:** Add protected action page

**Issue:** https://www.notion.so/saladtech/Protected-Action-page-3a516fccc3474ceea00c92847e950ce9

<img width="1276" alt="image" src="https://github.com/user-attachments/assets/12058c92-f10c-422f-90c5-f3ff0bfe6330">

2024-08-20 13:54 UTC, vitto-moz commented on packages/web-app/src/modules/protected-action/ProtectedActionPageContainer.tsx
> +  verifyWithPasskey: () => {},
https://github.com/SaladTechnologies/salad-applications/pull/1168#discussion_r1711245350

2024-08-21 10:43 UTC, vitto-moz requested changes

2024-08-21 10:43 UTC, vitto-moz commented on packages/web-app/src/modules/protected-action/components/ProtectedActionPage.tsx
> +    verifyWithBackupCodeClick?.(values.backupCode)
```suggestion
    verifyBackupCode?.(values.backupCode)
```

2024-08-21 10:43 UTC, vitto-moz commented on packages/web-app/src/modules/protected-action/components/ProtectedActionPage.tsx
> +          <Button variant="outlined" label="Cancel" onClick={backToPreviousPageClick} />
```suggestion
          <Button variant="outlined" label="Cancel" onClick={onBackToPreviousPageClick} />
```

2024-08-21 10:43 UTC, vitto-moz commented on packages/web-app/src/modules/protected-action/components/ProtectedActionPage.tsx
> +            onSubmit={handleVerifyWithBackupCodeSubmit}
```suggestion
            onSubmit={handleVerifyBackupCodeSubmit}
```

2024-08-21 10:43 UTC, vitto-moz commented on packages/web-app/src/modules/protected-action/components/ProtectedActionPage.tsx
> +                onClick={verifyWithPasskeyClick}
```suggestion
                onClick={onVerifyPasskeyClick}
```

2024-08-21 10:43 UTC, vitto-moz commented on packages/web-app/src/modules/protected-action/components/ProtectedActionPage.tsx
> +  verifyWithPasskeyClick,
```suggestion
  onVerifyPasskeyClick,
```

2024-08-21 10:43 UTC, vitto-moz commented on packages/web-app/src/modules/protected-action/components/ProtectedActionPage.tsx
> +  backToPreviousPageClick,
```suggestion
  onBackToPreviousPageClick,
```

2024-08-21 10:46 UTC, Maks19 commented on packages/web-app/src/modules/protected-action/components/ProtectedActionPage.tsx
> +    verifyWithBackupCodeClick?.(values.backupCode)
Any reason to change it?

2024-08-21 10:47 UTC, Maks19 commented on packages/web-app/src/modules/protected-action/components/ProtectedActionPage.tsx
> +            onSubmit={handleVerifyWithBackupCodeSubmit}
Why do we need to remove `With`?

2024-08-21 10:49 UTC, vitto-moz commented on packages/web-app/src/modules/protected-action/components/ProtectedActionPage.tsx
> +    verifyWithBackupCodeClick?.(values.backupCode)
the functionality is about verifying the code itself, right?

2024-08-21 10:50 UTC, vitto-moz commented on packages/web-app/src/modules/protected-action/components/ProtectedActionPage.tsx
> +            onSubmit={handleVerifyWithBackupCodeSubmit}
the functionality is about verifying the code itself, right?

2024-08-21 11:59 UTC, vitto-moz requested changes

2024-08-21 11:59 UTC, vitto-moz commented on packages/web-app/src/modules/protected-action/ProtectedActionPageContainer.tsx
> +  verifyWithBackupCodeClick: () => {},
```suggestion
  verifyWithBackupCode: () => {},
```

2024-08-21 11:59 UTC, vitto-moz commented on packages/web-app/src/modules/protected-action/ProtectedActionPageContainer.tsx
> +  onVerifyPasskeyClick: () => {},
```suggestion
  onVerifyWithPasskeyClick: () => {},
```

2024-08-21 12:40 UTC, vitto-moz approved these changes

2024-08-21 12:49 UTC, merged