[WebApp] Edit passkey name
SaladTechnologies/salad-applications pull request #1193
Opened 2024-08-27 16:36 UTC by Maks19

**Description:** Edit passkey name 

**Issue:** https://www.notion.so/saladtech/FE-Edit-passkey-name-bf4f9a16515a450f9752e0cb350f084a

<img width="378" alt="image" src="https://github.com/user-attachments/assets/54c220e2-5c62-4bf1-9f5c-9597619c7c15">

2024-08-28 14:44 UTC, vitto-moz requested changes

2024-08-28 14:44 UTC, vitto-moz commented on packages/web-app/src/modules/passkey-setup/PasskeyStore.tsx
> -  @action.bound
don't remove this line it leads to the lost context of mobx store in `setRegisterPasskeyStatus`

2024-08-28 14:56 UTC, vitto-moz commented
long passkey name intersects with a date
![image](https://github.com/user-attachments/assets/ef612360-d846-400a-8229-e22c858db68b)

2024-08-28 15:09 UTC, vitto-moz commented
the submit button looks not to be aligned with a rest of UI
![image](https://github.com/user-attachments/assets/0ab7e909-756c-4b10-af19-6a7170cad525)

2024-08-28 15:18 UTC, vitto-moz commented
After the first submit there are no input controls on focus and editing (there are no submit and undo icons)
![image](https://github.com/user-attachments/assets/029e1bdc-99df-4c4c-8959-1275553711ea)

2024-08-28 18:01 UTC, Maks19 commented on packages/web-app/src/modules/passkey-setup/PasskeyStore.tsx
> +
When do we need `unknown` status?

2024-08-28 18:03 UTC, Maks19 commented
> there is a unnecessary space on the input focus ![image](https://private-user-images.githubusercontent.com/19843391/362345752-2eb4a090-72e3-4817-827e-d938cfad5162.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjQ4NjgzNDEsIm5iZiI6MTcyNDg2ODA0MSwicGF0aCI6Ii8xOTg0MzM5MS8zNjIzNDU3NTItMmViNGEwOTAtNzJlMy00ODE3LTgyN2UtZDkzOGNmYWQ1MTYyLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA4MjglMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwODI4VDE4MDA0MVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTUzZmU4YWUwNjc5Y2RjNzAwNzg3YjVmZmVhNTAxYWJiMzk4Njg5Mzc1ZjM2NDQ4YzBmMGI2NWQxYWU1YzE2NmYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.iOwU0ZViNZ4DUjhDbk_ed8BxYq8GjLXIJKnjhjEY3cU)

It's necessary because there are two icons
I used the same input as we have for other usernames

2024-09-02 13:24 UTC, vitto-moz commented on packages/web-app/src/modules/passkey-setup/PasskeyStore.tsx
> +
`unknown` is the initial status - before the submitting process started.

2024-09-02 16:37 UTC, vitto-moz commented on packages/web-app/src/modules/passkey-setup/PasskeyStore.tsx
> -  @action.bound
fixed

2024-09-02 16:41 UTC, vitto-moz commented
@Maks19 I've added commits to cover all the mentioned issues - please, check and we can discuss if needed

2024-09-03 09:20 UTC, vitto-moz submitted a review, later dismissed

2024-09-03 13:20 UTC, merged