[WebApp] Add challenge sudo mode
SaladTechnologies/salad-applications pull request #1194
Opened 2024-08-30 14:19 UTC by Maks19

**Description:** Add challenge sudo mode for Google SSO and PayPal

**Issue:** https://www.notion.so/saladtech/FE-Intercept-failed-requests-for-Paypal-and-Google-SSO-52b362dd2de3430c97fbb51b3baacdef

2024-09-03 14:07 UTC, vitto-moz requested changes

2024-09-03 14:07 UTC, vitto-moz commented on packages/web-app/src/modules/protected-action/utils.tsx
> +      break
why cannot we make this condition handled plain - so just add `ChallengeSudoModeTrigger` enum values into `ChallengeSudoModeTrigger`

2024-09-03 14:07 UTC, vitto-moz commented on packages/web-app/src/modules/account-views/account-views/components/GoogleSignInForm.tsx
> +      const response = await challengeSudoMode(ChallengeSudoModeTrigger.GoogleSignIn)
we should not execute requests and handle responses in a component - let's use store for that

2024-09-03 17:34 UTC, Maks19 commented on packages/web-app/src/modules/account-views/account-views/components/GoogleSignInForm.tsx
> +      const response = await challengeSudoMode(ChallengeSudoModeTrigger.GoogleSignIn)
Fixed

2024-09-03 17:34 UTC, Maks19 commented on packages/web-app/src/modules/protected-action/utils.tsx
> +      break
Fixed

2024-09-03 17:34 UTC, Maks19 commented on packages/web-app/src/modules/account-views/account-views/components/PayPalLoginButton.tsx
> +      const response = await challengeSudoMode(ChallengeSudoModeTrigger.PayPalLogIn)
Fixed

2024-09-03 21:14 UTC, vitto-moz requested changes

2024-09-03 21:14 UTC, vitto-moz commented on packages/web-app/src/modules/account-views/account-views/components/GoogleHiddenSignInForm.tsx
> +      ref={hiddenFormRef}
shouldn't we use `React.forwardRef` to make it work correct?

2024-09-03 21:14 UTC, vitto-moz commented on packages/web-app/src/modules/account-views/account-views/components/GoogleSignInForm.tsx
> +      googleSignInChallengeSudoMode(hiddenFormRef.current.submit.bind(hiddenFormRef.current))
```suggestion
      const signInWithGoogle = hiddenFormRef.current.submit.bind(hiddenFormRef.current)
      googleSignInChallengeSudoMode(signInWithGoogle )
```

2024-09-03 21:14 UTC, vitto-moz commented on packages/web-app/src/modules/account-views/account-views/components/GoogleSignInForm.tsx
> +  googleSignInChallengeSudoMode: (googleSignIn: () => void) => void
```suggestion
  googleSignInChallengeSudoMode: (signInWithGoogle: () => void) => void
```

2024-09-03 21:14 UTC, vitto-moz commented on packages/web-app/src/modules/auth/AuthStore.tsx
> +  googleSignInChallengeSudoMode = async (googleSignIn: () => void): Promise<void> => {
```suggestion
  signInWithGoogleChallengeSudoMode= async (signInWithGoogle: () => void): Promise<void> => {
```

2024-09-03 21:14 UTC, vitto-moz commented on packages/web-app/src/modules/auth/AuthStore.tsx
> +  payPalLogInChallengeSudoMode = async (): Promise<void> => {
```suggestion
  sighInWithPayPalChallengeSudoMode= async (): Promise<void> => {
```

2024-09-03 21:14 UTC, vitto-moz commented on packages/web-app/src/modules/profile/ProfileStore.tsx
> +let timeoutId: NodeJS.Timeout
let's make it a private property named `loadPayPalIdTimeout` of a class `ProfileStore` and place near `loadPayPalId` property

2024-09-04 08:32 UTC, Maks19 commented on packages/web-app/src/modules/profile/ProfileStore.tsx
> +let timeoutId: NodeJS.Timeout
Fixed

2024-09-04 08:32 UTC, Maks19 commented on packages/web-app/src/modules/auth/AuthStore.tsx
> +  payPalLogInChallengeSudoMode = async (): Promise<void> => {
Fixed

2024-09-04 08:32 UTC, Maks19 commented on packages/web-app/src/modules/auth/AuthStore.tsx
> +  googleSignInChallengeSudoMode = async (googleSignIn: () => void): Promise<void> => {
Fixed

2024-09-04 08:32 UTC, Maks19 commented on packages/web-app/src/modules/account-views/account-views/components/GoogleSignInForm.tsx
> +  googleSignInChallengeSudoMode: (googleSignIn: () => void) => void
Fixed

2024-09-04 08:32 UTC, Maks19 commented on packages/web-app/src/modules/account-views/account-views/components/GoogleSignInForm.tsx
> +      googleSignInChallengeSudoMode(hiddenFormRef.current.submit.bind(hiddenFormRef.current))
Fixed

2024-09-04 08:33 UTC, Maks19 commented on packages/web-app/src/modules/account-views/account-views/components/GoogleHiddenSignInForm.tsx
> +      ref={hiddenFormRef}
Fixed

2024-09-04 08:33 UTC, Maks19 commented on packages/web-app/src/modules/account-views/account-views/AccountContainer.tsx
> +  payPalLogInChallengeSudoMode: store.auth.payPalLogInChallengeSudoMode,
Fixed
used `logInWithPayPalChallengeSudoMode`

2024-09-04 08:33 UTC, Maks19 commented on packages/web-app/src/modules/protected-action/ProtectedActionPageContainer.tsx
> +  isPendingProtectedActionExist: !!store.auth.pendingProtectedAction,
Changed it

2024-09-04 12:10 UTC, vitto-moz approved these changes

2024-09-04 12:16 UTC, merged