[SALAD-22778] WebApp: Demand monitor page connect
SaladTechnologies/salad-applications pull request #1220
Opened 2024-11-11 18:04 UTC by vitto-moz

![image](https://github.com/user-attachments/assets/6a2ce539-c6d0-4eb6-b7a4-e1bc3930ee28)

2024-11-12 12:28 UTC, Maks19 requested changes

2024-11-12 12:28 UTC, Maks19 commented on packages/web-app/src/modules/demand-monitor-views/DemandMonitorPage/DemandMonitorTable/DemandMonitorTable.tsx
> +    toJS(demandedHardwarePerformanceList),
Why do you need `toJS` here?

2024-11-12 12:28 UTC, Maks19 commented on packages/web-app/src/modules/demand-monitor-views/DemandMonitorPage/DemandMonitorTable/utils.ts
> +}
```suggestion
export const sortHardwareDemandPerformance = (
  demandedHardwarePerformanceList: DemandedHardwarePerformance[],
  sortOrder: 'ascending' | 'descending' | 'none',
  sortRule?: DemandMonitorTableSortRule,
): DemandedHardwarePerformance[] => {
  if (!sortRule) {
    return demandedHardwarePerformanceList
  }

  const sortedList = demandedHardwarePerformanceList.sort(sortRule)
  return sortOrder === 'ascending' ? sortedList.reverse() : sortedList;
}
```

2024-11-12 12:28 UTC, Maks19 commented on packages/web-app/src/modules/demand-monitor-views/DemandMonitorPage/DemandMonitorTable/DemandMonitorTable.tsx
> +  }
```suggestion

  const sortedDemandedHardwarePerformanceList = sortHardwareDemandPerformance(
    toJS(demandedHardwarePerformanceList),
    sortOrder.sorted,
    demandMonitorTableColumns[sortOrder.columnKey].sortRule,
  )
```

2024-11-12 14:16 UTC, vitto-moz commented on packages/web-app/src/modules/demand-monitor-views/DemandMonitorPage/DemandMonitorTable/DemandMonitorTable.tsx
> +                    {/* <Text variant="baseXS">{recommendedSpecs.storage}</Text> */}
we probably will make this value hardcoded, we will have a decision today

2024-11-12 14:24 UTC, vitto-moz commented on packages/web-app/src/modules/demand-monitor-views/DemandMonitorPage/DemandMonitorTable/DemandMonitorTable.tsx
> +    toJS(demandedHardwarePerformanceList),
MobX  stores the data as a proxy object, so it doesn't have all the regular methods of `Array`, for example, that's why we need to transform it to related data type

2024-11-12 17:54 UTC, vitto-moz commented on packages/web-app/src/modules/demand-monitor-views/DemandMonitorPage/DemandMonitorPage.tsx
> +    fetchDemandedHardwarePerformanceList()
yes, re-fetch once per hour functionality - added

2024-11-12 17:54 UTC, vitto-moz commented on packages/web-app/src/modules/demand-monitor-views/DemandMonitorPage/DemandMonitorTable/DemandMonitorTable.tsx
> +    toJS(demandedHardwarePerformanceList),
`toJS` - removed, no longer needed

2024-11-12 22:56 UTC, Maks19 approved these changes

2024-11-13 13:08 UTC, Maks19 approved these changes

2024-11-13 13:16 UTC, merged