[SALAD-23116] WebApp - Connect demand alerts page
SaladTechnologies/salad-applications pull request #1243
Opened 2024-12-13 01:12 UTC by Maks19

**Description:** Connect demand alerts page

2024-12-13 20:14 UTC, Maks19 commented on packages/web-app/src/modules/demand-alerts-views/DemandAlertsPage/DemandAlertsList/DemandAlertsList.tsx
> +  }
Agree
Changed

2025-01-13 16:29 UTC, vitto-moz requested changes

2025-01-13 16:29 UTC, vitto-moz commented on packages/web-app/src/modules/demand-alerts-views/DemandAlertsPage/DemandAlertsSetUp/utils.ts
> +}
faster alternative
```suggestion

export const createNewSubscriptionErrorTexts: Partial<Record<SubscribeToDemandAlertStatus, string>> = {
  [SubscribeToDemandAlertStatus.FAILURE]: 'Something went wrong. Please try again later',
  [SubscribeToDemandAlertStatus.ALREADY_EXISTS]: 'An alert with this GPU and Demand Scenario already exists.',
  [SubscribeToDemandAlertStatus.INVALID_GPU]: 'The GPU configuration provided is invalid.',
}

```

2025-01-13 16:29 UTC, vitto-moz commented on packages/web-app/src/modules/demand-alerts-views/DemandAlertsStore.tsx
> +  private mapErrorToSubscribeToDemandAlertStatus(error: any): SubscribeToDemandAlertStatus {
```suggestion
  private getSubscribeToDemandAlertStatusFromError(error: any): SubscribeToDemandAlertStatus {
```

2025-01-13 16:29 UTC, vitto-moz commented on packages/web-app/src/modules/demand-alerts-views/DemandAlertsStore.tsx
> +  private mapErrorToSubscribeToDemandAlertStatus(error: any): SubscribeToDemandAlertStatus {
```suggestion
  private mapErrorToSubscribeToDemandAlertStatus(error: AxiosError<{ type: string }>): SubscribeToDemandAlertStatus {
```

2025-01-13 16:29 UTC, vitto-moz commented on packages/web-app/src/modules/demand-alerts-views/DemandAlertsStore.tsx
> +      case 'subscription:create:already-exists':
better to store like constants, can be like this : 
```
enum SubscribeToDemandAlertErrorType {
  AlreadyExist= 'subscription:create:already-exists',
 .... 
}

2025-01-13 16:29 UTC, vitto-moz commented on packages/web-app/src/modules/demand-alerts-views/DemandAlertsStore.tsx
> +      case 'subscription:create:already-exists':
optional 
```
const SubscribeToDemandAlertStatusByErrorType<SubscribeToDemandAlertErrorType, SubscribeToDemandAlertStatus> ={
  [SubscribeToDemandAlertErrorType.AlreadyExist] = SubscribeToDemandAlertStatus.ALREADY_EXISTS
}

2025-01-13 16:29 UTC, vitto-moz commented on packages/web-app/src/modules/demand-alerts-views/DemandAlertsStore.tsx
> +  UNKNOWN = 'unknown',
let's avoid UPPECASE properties in favor of Capitalized as it written in [TS Documentation  ](https://www.typescriptlang.org/docs/handbook/enums.html)

2025-01-13 16:29 UTC, vitto-moz commented on packages/web-app/src/modules/demand-alerts-views/DemandAlertsStore.tsx
> +  UNKNOWN = 'unknown',
let's avoid UPPECASE properties in favor of Capitalized as it written in [TS Documentation  ](https://www.typescriptlang.org/docs/handbook/enums.html)

2025-01-13 16:29 UTC, vitto-moz commented on packages/web-app/src/modules/demand-alerts-views/DemandAlertsPage/DemandAlertsList/DemandAlertsList.tsx
> +            const isCurrentDemandedSubscriptionId = currentDemandedSubscriptionId === demandAlertSubscription.id
```suggestion
            const isCurrentDemandedSubscription = currentDemandedSubscriptionId === demandAlertSubscription.id
```

2025-01-13 16:44 UTC, Maks19 commented on packages/web-app/src/modules/demand-alerts-views/DemandAlertsStore.tsx
> +  private mapErrorToSubscribeToDemandAlertStatus(error: any): SubscribeToDemandAlertStatus {
`Catch clause variable type annotation must be 'any' or 'unknown' if specified.ts(1196)`. Any reason to specify it?

2025-01-13 16:48 UTC, Maks19 commented on packages/web-app/src/modules/demand-alerts-views/DemandAlertsPage/DemandAlertsList/DemandAlertsList.tsx
> +    demandAlertSubscriptionList?.length > 0 && (
'demandAlertSubscriptionList.length' is possibly 'undefined'

2025-01-13 16:55 UTC, vitto-moz commented on packages/web-app/src/modules/demand-alerts-views/DemandAlertsPage/DemandAlertsList/DemandAlertsList.tsx
> +    demandAlertSubscriptionList?.length > 0 && (
you already handled it with `?`
```
// undefined > 0
false

2025-01-13 16:56 UTC, Maks19 commented on packages/web-app/src/modules/demand-alerts-views/DemandAlertsPage/DemandAlertsList/DemandAlertsList.tsx
> +    demandAlertSubscriptionList?.length > 0 && (
Nope
It doesn't work because we need length

2025-01-13 17:08 UTC, Maks19 commented on packages/web-app/src/modules/demand-alerts-views/DemandAlertsStore.tsx
> +  private mapErrorToSubscribeToDemandAlertStatus(error: any): SubscribeToDemandAlertStatus {
We cannot guarantee that the error in the catch block will be an Error instance ahead of time (It's can be RangeError for example), so TypeScript sets its type to [unknown]. We would need to check instanceof if we want to use a specified error type and I think we don't need it.

It's TS error if you try to specify an error in catch.

2025-01-13 17:24 UTC, vitto-moz commented on packages/web-app/src/modules/demand-alerts-views/DemandAlertsStore.tsx
> +    }
let's put it outside of functions scope to constants

2025-01-13 17:44 UTC, vitto-moz approved these changes

2025-01-13 17:53 UTC, merged