Add build config for linux, add build icons
SaladTechnologies/salad-applications pull request #531
Opened 2020-09-18 01:42 UTC by Krish120003

Still need to add the 512x512 icon into the build/icons folder.

2020-09-18 20:40 UTC, seniorquico commented
@Krish120003 The Linux package assets have been merged into the `master` branch.

2020-09-19 00:25 UTC, Krish120003 reviewed
Add build config for linux

2020-09-19 00:29 UTC, seniorquico requested changes

2020-09-19 00:29 UTC, seniorquico commented on packages/desktop-app/electron-builder.json
> +    "depends": ["libappindicator1", "libnotify-bin"]
Do we know that explicitly declaring the dependencies is required? Do they not automatically include these dependencies in their template?

2020-09-19 00:29 UTC, seniorquico commented on packages/desktop-app/electron-builder.json
> +    "target": ["deb", "rpm", "snap"],
Let's also include the AppImage target:

```suggestion
    "target": ["AppImage", "deb", "rpm", "snap"],
```

I'm not sure how popular this format is, but it was easy to download & run to app.

2020-09-20 00:40 UTC, seniorquico commented on packages/desktop-app/electron-builder.json
> +    "depends": ["libappindicator1", "libnotify-bin"]
I created a `.rpm` build without explicitly declaring dependencies, and I tested it on CentOS 8. I was able to confirm that it does _not_ include `libappindicator1` as a dependency. The necessary dependency appears to be `libappindicator-gtk3` (e.g. Chrome & Slack depend on this package).

2020-09-25 00:17 UTC, closed without merging