WIP: Add Zendesk authentication
SaladTechnologies/salad-applications pull request #575
Opened 2020-11-18 18:01 UTC by scottcinatl

2020-11-20 22:12 UTC, scottcinatl commented
@seniorquico Verified that the token I was receiving was for the correct account, but I noticed Zendesks own calls to verify the authentication was denied due to the request coming from a unknown domain (local).

![Capture](https://user-images.githubusercontent.com/28833112/99854691-2abc1980-2b3a-11eb-99a2-ed9c7aee188f.PNG)

So I am not sure how to go about verification on the Zendesk side of things that requests are being properly associated with the user account.

2020-11-22 04:41 UTC, seniorquico requested changes

2020-11-22 04:41 UTC, seniorquico commented on packages/web-app/src/Store.ts
> +      // initialize Zendesk
nit: The comment looks redundant; the function name describes what's going on.

2020-11-22 04:41 UTC, seniorquico commented on packages/web-app/src/Store.ts
> +      this.zendesk.prefillProfile(profile.username, profile.email)
nit: The comment looks redundant; the field & function names describe what's going on.

2020-11-22 04:41 UTC, seniorquico commented on packages/web-app/src/Store.ts
> +      this.zendesk.intializeZendesk();
The only observable used within this `autorun` block is the `isAuthenticated` flag. This changes when the user logs in & logs out. It's possible `initializeZendesk` will be called multiple times in a single app session. As it stands now, this will result in creating multiple `<script ...>` tags to load the Zendesk web widget (one at app startup & one every time the user logs in or logs out). This should probably be split... initializing `window.zESettings` and injecting the `<script ...>` tag should only happen once for the entire app session. This `autorun` block can then be used to react to changes in the authentication state.

2020-11-22 04:41 UTC, seniorquico commented on packages/web-app/src/modules/zendesk/Zendesk.ts
> +      window.zE && window.zE('webWidget', 'prefill', {
What happens if the Zendesk web widget scripts haven't loaded by the time this function is called? Wouldn't this just be skipped and the form left with empty values/defaults?

Maybe a better question... is this still necessary when we're using the authentication? It may very well be, but it kinda feels redundant given we've already passed along a signed JWT that contained this info.

2020-11-23 22:22 UTC, scottcinatl commented on packages/web-app/src/modules/zendesk/Zendesk.ts
> +      window.zE && window.zE('webWidget', 'prefill', {
With my latest [commit](https://github.com/SaladTechnologies/salad-applications/pull/575/commits/a432d4925a8bcaa874172d5d6ca5e5f0e6a5f953), I moved the inject of the Zendesk to always fire before any authentication process occurs, which includes the prefilling of the form. So there should never be a case when a prefill is attempted by an unauthenticated user. 

After looking around in Zendesk's docs, it does not seem that submitting a successful token triggers and auto filling of form fields. So the built in prefill function seems to be the way to go. As for that information, are you suggesting that I should be getting that info by decoding the JWT instead of getting the information from the store?

2020-11-30 22:06 UTC, seniorquico requested changes

2020-11-30 22:06 UTC, seniorquico commented on packages/web-app/src/modules/zendesk/Zendesk.ts
> +
This should clear any pending "reauthenticate" timer before calling the logout function (we know it won't succeed, so just bail).


```ts    if (this.reauthenticateRetryTimeout) {
      clearTimeout(this.reauthenticateRetryTimeout)
      this.reauthenticateRetryTimeout = undefined
    }```

2020-11-30 22:16 UTC, seniorquico commented on packages/web-app/src/modules/zendesk/Zendesk.ts
> +      window.zE && window.zE('webWidget', 'prefill', {
Retry logic added in 9532ea4.

2020-11-30 23:22 UTC, seniorquico approved these changes

2020-12-01 21:55 UTC, merged