Added select earnings range feature to earnings chart
SaladTechnologies/salad-applications pull request #578
Opened 2020-11-25 21:59 UTC by scottcinatl

Adds the ability for a user to select a range of earnings on the earning chart and view the sum of the selected range. 

![chart range](https://user-images.githubusercontent.com/28833112/100285289-7b11ed80-2f25-11eb-922d-65e0d940c334.gif)

@dsarfati In the original photo for the task, it showed the tooltips showing for both the start and end of the range selected. However, it does not seem like you can have two tooltips showing at the same time in recharts. So I just added those time values to one tooltip. 

![feature request chart range_LI](https://user-images.githubusercontent.com/28833112/100285781-566a4580-2f26-11eb-9de7-2a4892e8284f.jpg)

2020-12-02 16:41 UTC, Fvn556 commented
ooh this is cool

2020-12-09 20:36 UTC, seniorquico requested changes

2020-12-09 20:36 UTC, seniorquico commented on packages/web-app/src/components/elements/Segments/Segments.tsx
> +              [classes.active]: this.state[option.name],
Why do these have `@ts-ignore`? I would like to avoid these escape hatch comments as much as possible.

2020-12-09 20:36 UTC, seniorquico commented on packages/web-app/src/modules/earn-views/components/EarningChart.tsx
> +      { name: "24HR", action: viewLast24Hours },
Consistent formatting with the two options below? e.g. "24 Hours"

2020-12-09 20:36 UTC, seniorquico commented on packages/web-app/src/modules/earn-views/components/EarningChart.tsx
> +          <>
This is a complex render function, with several arrow functions. Is this a performance hotspot? How's the performance on lower-end setups?

2020-12-09 22:21 UTC, scottcinatl commented on packages/web-app/src/modules/earn-views/components/EarningChart.tsx
> +      { name: "24HR", action: viewLast24Hours },
Dan wanted the naming to be consistent with the Earning History summary. 

![24 hour](https://user-images.githubusercontent.com/28833112/101695622-bd5d2380-3a29-11eb-955a-49aea5e010aa.PNG)

2020-12-09 22:41 UTC, scottcinatl commented on packages/web-app/src/modules/balance/BalanceStore.ts
> +    return this.getEarningWindows(this.daysShowingEarnings)
No, this function is only getting called anytime the state of `this.daysShowingEarnings` is updated, which only occurs when a user switches earning day view (e.g., 24HR to 7 days).

2020-12-10 23:29 UTC, seniorquico approved these changes

2020-12-10 23:40 UTC, merged