Added MinecraftUsername component to Profile page
SaladTechnologies/salad-applications pull request #595
Opened 2020-12-21 19:19 UTC by scottcinatl

2020-12-29 01:24 UTC, seniorquico requested changes

2020-12-29 01:24 UTC, seniorquico commented on packages/web-app/src/modules/reward/RewardStore.ts
> +        } else if (error.message === 'Minecraft Username not available') {
Shouldn't this be checking for a `redemptions:requires:minecraftUsername` problem?

2020-12-29 18:25 UTC, scottcinatl commented on packages/web-app/src/modules/reward/RewardStore.ts
> +        } else if (error.message === 'Minecraft Username not available') {
I am not sure if this is the best way to go about this, but here is my [commit](https://github.com/SaladTechnologies/salad-applications/pull/595/commits/b6b2c921a1263a76f4a6fdfd20ab2d32a7bfcdf6) of what I have implemented so far. Might need more refactoring?

2021-01-06 05:21 UTC, seniorquico requested changes

2021-01-06 05:21 UTC, seniorquico commented on packages/web-app/src/axiosFactory.ts
> +export const REQUIRES_MINECRAFT_USERNAME = 'Redemption requires a Minecraft Username.'
This should be inlined.

2021-01-06 05:21 UTC, seniorquico commented on packages/web-app/src/modules/account-views/account-views/components/Account.tsx
> +          <MinecraftUsernameContainer />
Just curious... why not `EditMinecraftUsername` to match the field above?

2021-01-06 05:21 UTC, seniorquico commented on packages/web-app/src/modules/account-views/account-views/MinecraftUsernameContainer.ts
> +export const MinecraftUsernameContainer = connect(mapStoreToProps, MinecraftUsername)
Is this the desired pattern, that each field in the form be connected to the store? Why isn't the overall form being connected, and the fields just acting as simple components with basic props?

2021-01-06 05:21 UTC, seniorquico commented on packages/web-app/src/modules/account-views/account-views/components/MinecraftUsername.tsx
> +        <P>Add your Minecraft username in order to redeem some sweet Minecraft skins!</P>
Is this the desired text? First, "skins" aren't really a Minecraft thing... they're "capes". Second, I think we're going to support subscriptions to private servers & loot boxes. Double check on the copy.

2021-01-06 05:21 UTC, seniorquico commented on packages/web-app/src/modules/profile/ProfileStore.ts
> +      let patch = yield this.axios.patch('/api/v1/profile', { minecraftUsername: minecraftUsername })
See the note about the API change on the Notion card. Easy fix:

```suggestion
      let patch = yield this.axios.patch('/api/v1/profile', { extensions: { minecraftUsername }})
```

2021-01-06 05:21 UTC, seniorquico commented on packages/web-app/src/modules/profile/ProfileStore.ts
> +    if (this.currentProfile === undefined) return
nit:

```suggestion
    if (this.currentProfile === undefined) {
      return
    }
```

2021-01-06 05:21 UTC, seniorquico commented on packages/web-app/src/modules/profile/models/Profile.ts
> +  minecraftUsername?: string
```suggestion
  extensions?: {
    minecraftUsername?: string
  }
```

2021-01-06 05:21 UTC, seniorquico commented on packages/web-app/src/modules/reward-views/RewardDetailsContainer.tsx
> +  hasMinecraftUsername: store.profile.currentProfile?.minecraftUsername !== undefined,
```suggestion
  hasMinecraftUsername: store.profile.currentProfile?.extensions?.minecraftUsername !== undefined,
```

2021-01-06 05:21 UTC, seniorquico commented on packages/web-app/src/modules/reward-views/components/RewardHeaderBar.tsx
> +  hasMinecraftUsername: boolean
Is there a better way to genericize this? Otherwise, won't we end up with dozens of flags for different types of (future) requirements?

2021-01-06 05:21 UTC, seniorquico commented on packages/web-app/src/modules/reward-views/components/RewardHeaderBar.tsx
> +    const requiresMinecraftUsername = reward?.tags?.includes('requires-minecraft-username') && !hasMinecraftUsername
This feels like business logic, something that shouldn't be inside the view layer.

2021-01-06 05:21 UTC, seniorquico commented on packages/web-app/src/modules/reward-views/components/RewardHeaderBar.tsx
> +              onClick={requiresMinecraftUsername ? this.furtherActionRequired : this.handleRedeem}
If `furtherActionRequired` is a generic prop, with a specific action (routing to the profile page to set the Minecraft username), then it feels like these other bits should be moved outside the component. I think this helps with preparing for different, future reward requirements.

2021-01-06 23:01 UTC, scottcinatl commented on packages/web-app/src/modules/account-views/account-views/components/Account.tsx
> +          <MinecraftUsernameContainer />
The `EditUsername` component only allows the ability to edit the username, you can not create a username in that component. Whereas the `MinecraftUsername` component allows for creation and updating.

2021-01-06 23:02 UTC, scottcinatl commented on packages/web-app/src/modules/account-views/account-views/components/MinecraftUsername.tsx
> +        <P>Add your Minecraft username in order to redeem some sweet Minecraft skins!</P>
No, yeah this is placeholder text. I will add a TODO flag around this and ping Jared/Dan to get the desired copy.

2021-01-15 00:51 UTC, seniorquico requested changes

2021-01-15 00:51 UTC, seniorquico commented on packages/web-app/src/modules/profile/ProfileStore.ts
> +        },
The `PATCH` method is cool with merging in changes to top-level properties... but it doesn't preserve any child properties. For the most part, this is why we don't frequently use nested objects. We need to explicitly preserve any other extension properties, otherwise this will be _deleting_ the others.

```suggestion
        extensions: this.currentProfile.extensions === undefined
          ? {
              minecraftUsername: minecraftUsername,
            }
          : {
              ...this.currentProfile.extensions,
              minecraftUsername: minecraftUsername,
            },
```

2021-01-15 16:33 UTC, seniorquico approved these changes

2021-01-15 16:36 UTC, merged