Added modal notification for non compatible GPU start clicks
SaladTechnologies/salad-applications pull request #612
Opened 2021-01-21 22:26 UTC by scottcinatl

Adds a new modal notification that pops up when a user clicks the start button if they do not have a compatible GPU. This modal provides information about compatibility and gives the user the option to switch to CPU mining instead.

2021-01-22 20:00 UTC, seniorquico requested changes

2021-01-26 00:29 UTC, seniorquico requested changes

2021-01-26 00:29 UTC, seniorquico commented on packages/web-app/src/modules/error-views/NotCompatibleErrorContainer.ts
> +    store.analytics.trackButtonClicked(currentPath, 'switch_mining_type_button', 'Switch Mining Type Button', 'enabled')
Future refactor idea... but why can't the `trackButtonClicked` method pull the `window && window.location.pathname` value? It would save having to duplicate this all over.

2021-01-26 00:29 UTC, seniorquico commented on packages/web-app/src/modules/machine-views/TitleStartButtonContainer.ts
> +      store.ui.showModal('/errors/not-compatible')
```suggestion
    if (isDisabled || (notCompatible && !isRunning)) {
      store.analytics.trackButtonClicked(currentPath, 'start_button', 'Start Button', isDisabled ? 'disabled' : 'enabled')
      store.ui.showModal('/errors/not-compatible')
```

2021-01-26 00:29 UTC, seniorquico commented on packages/web-app/src/modules/salad-bowl/definitions/requirements.tsx
> +      system.memLayout.reduce((amount, memory) => amount + memory.size, 0) >= ram * 1024 * 1024
```suggestion
  preferences.cpuOverridden || (preferences.cpu && system.memLayout !== undefined && system.memLayout.reduce((amount, memory) => amount + memory.size, 0) >= ram * 1024 * 1024)
```

2021-01-26 00:29 UTC, seniorquico commented on packages/web-app/src/modules/salad-bowl/definitions/requirements.tsx
> +      })
```suggestion
  preferences.gpuOverridden || (preferences.gpu &&
      system.graphics !== undefined &&
      system.graphics.controllers.some((controller) => {
        const intel = controller.vendor.toLowerCase().includes('intel')
        if (intel) {
          return false
        }

        const nvidia = controller.vendor.toLowerCase().includes('nvidia')
        if (framework === 'cuda' && !nvidia) {
          return false
        }

        if (framework === 'opencl' && nvidia) {
          return false
        }

        const amount = controller.memoryTotal !== undefined ? controller.memoryTotal : controller.vram
        return amount >= vram * 0.9
      }))
```

2021-01-26 00:29 UTC, seniorquico commented on packages/web-app/src/modules/error-views/components/NotCompatibleErrorPage.tsx
> +      <ErrorPage title={`No Compatible ${gpuMiningEnabled ? 'GPU' : 'CPU'} Detected`} onCloseClicked={onCloseClicked}>
This ternary runs multiple times. Can you pull it out and only run it once?

2021-01-26 00:42 UTC, scottcinatl commented on packages/web-app/src/modules/error-views/NotCompatibleErrorContainer.ts
> +    store.analytics.trackButtonClicked(currentPath, 'switch_mining_type_button', 'Switch Mining Type Button', 'enabled')
Yes, I will make a PR to address that.

2021-01-26 18:05 UTC, seniorquico approved these changes

2021-01-26 18:35 UTC, merged