Updated Fallback Error Modal
SaladTechnologies/salad-applications pull request #613
Opened 2021-01-22 23:22 UTC by scottcinatl

The updated Fallback Error Modal now provides the user with an opportunity to switch to an alternative mining type while also presenting them with helpful support links.

2021-01-23 00:34 UTC, seniorquico requested changes

2021-01-23 00:34 UTC, seniorquico commented on packages/web-app/src/modules/error-views/components/FallbackErrorPage.tsx
> +        title={`Salad is Unable to Run on your ${gpuMiningEnabled ? 'GPU' : 'CPU'}`}
The inline ternaries are repeated over and over... you should refactor them and only run the check once.

2021-01-23 00:34 UTC, seniorquico commented on packages/web-app/src/modules/zendesk/Zendesk.ts
> +        window.zE('webWidget:on', 'close', () => {
Is there a consequence to registering a callback every time the `openSupportTicket` function is called? Does it result in multiple subscriptions/callbacks? Should this be moved into the startup/initialization routine?

2021-01-26 17:37 UTC, scottcinatl commented on packages/web-app/src/modules/zendesk/Zendesk.ts
> +        window.zE('webWidget:on', 'close', () => {
I couldn't find any definitive answers in the documentation, but after playing around when the on close event, I believe that it can only be called/set during that close event. It doesn't seem like there is a way to set a standard on close event in the core settings for the widget.

2021-01-26 18:07 UTC, seniorquico requested changes

2021-01-26 18:07 UTC, seniorquico commented on packages/web-app/src/modules/error-views/components/FallbackErrorPage.tsx
> +          In the meantime, try switching to GPU mining so that you keep earning while we work to resolve your issue.
Should this text also be dynamic based on the currently selected mode (GPU vs CPU)?

2021-01-26 18:45 UTC, seniorquico approved these changes

2021-01-26 18:53 UTC, merged