Added Strapi Storefront Page prototype
SaladTechnologies/salad-applications pull request #616
Opened 2021-01-27 20:58 UTC by scottcinatl

Adds a prototype in Storybook of the existing home page while consuming mock Strapi data.

2021-03-01 22:32 UTC, seniorquico requested changes

2021-03-03 04:25 UTC, seniorquico requested changes

2021-03-03 04:25 UTC, seniorquico commented on packages/web-app/src/modules/storefront-views/blocks/StorefrontHeroBlock.tsx
> +        const heading = hero.reward?.name || hero.heading
These are flipped... We want to use the explicitly defined value first, and we want to _fallback_ to the reward (if defined).

```suggestion
        const heading = hero.heading || hero.reward?.name
```

2021-03-03 04:25 UTC, seniorquico commented on packages/web-app/src/modules/storefront-views/blocks/StorefrontHeroBlock.tsx
> +        const subHeading = hero.reward?.price ? `$${hero.reward?.price.toFixed(2)}` : hero.subheading
These are flipped... also, converting `hero.reward?.price` to a truthy/falsy value doesn't work when the price is free. For consistency, shouldn't a free price be transformed into a "FREE" string like in the reward list?

```suggestion
        const subHeading = hero.subheading || `$${hero.reward?.price.toFixed(2)}`
```

2021-03-03 04:25 UTC, seniorquico commented on packages/web-app/src/modules/storefront-views/blocks/StorefrontHeroBlock.tsx
> +        const buttonLink = hero.button_link ? hero.button_link : rewardRoute(hero.reward?.uuid)
nit:

```suggestion
        const buttonLink = hero.button_link || rewardRoute(hero.reward?.uuid)
```

2021-03-03 04:25 UTC, seniorquico commented on packages/web-app/src/modules/storefront-views/blocks/StorefrontHeroBlock.tsx
> +        const image = hero.reward?.image || `http://localhost:1337${hero.image.url}` // Change strapi api url to env variable when connecting
These are flipped... but also, please move the Strapi API origin into the `.env` file(s) and use the `URL` constructor to normalize the value. For example:

```ts
new URL(hero.image.url, 'http://localhost:1337')
```

The MDN docs note this works as expected, using the second paramter as a fallback:

> If `url` is a relative URL, `base` is required, and will be used as the base URL. If `url` is an absolute URL, a given `base` will be ignored.

2021-03-03 04:25 UTC, seniorquico commented on packages/web-app/src/modules/storefront-views/blocks/StorefrontRewardBlock.tsx
> +        {block.rewards.slice(0, 20).map((reward) => {
We should not be limiting this to the first 20 rewards.

2021-03-03 04:25 UTC, seniorquico commented on packages/web-app/src/modules/storefront-views/blocks/StorefrontHeroBlock.tsx
> +            buttonLink={buttonLink}
Shouldn't click actions follow the "standard" callback pattern? If no... why does this one pass a link down whereas the reward list passes a callback down? It seems weird to apply different.

2021-03-03 04:25 UTC, seniorquico commented on packages/web-app/src/modules/storefront-views/blocks/StorefrontRewardBlock.tsx
> +        viewAllRoute={block.buttons[0].link}
What if no buttons are defined?

2021-03-03 04:25 UTC, seniorquico commented on packages/web-app/src/modules/storefront/models/StorefrontRewardItemProps.ts
> +  image: string
```suggestion
  coverImage: string
  heroImage: string
```

2021-03-03 22:12 UTC, scottcinatl commented on packages/web-app/src/modules/storefront-views/blocks/StorefrontHeroBlock.tsx
> +            buttonLink={buttonLink}
Changed the `RewardItem` to match the `HeroItem` where each Reward is wrapped by our SmartLink component. This allows to take advantage of the ability of the `SmartLink` component to add tracking metrics if needed.

2021-03-03 22:15 UTC, scottcinatl commented on packages/web-app/src/modules/storefront-views/blocks/StorefrontContentBlock.tsx
> +export const StorefrontContentBlock = ({ block }: Props) => {
Consistency with the other block components, also if content blocks fields evolve to be more dynamic with the different banners shown in the Notion resource page (coulldn't find the link, but it the only with all possible designs of what a banner could be), the higher order block component could manage that decision logic what component renders.

2021-03-05 03:08 UTC, seniorquico approved these changes

2021-03-05 03:08 UTC, seniorquico commented on packages/web-app/src/modules/storefront/models/StorefrontBlockComponents.ts
> +  __component: string
In the future, leverage TypeScript's ["discriminated union" feature](https://www.typescriptlang.org/docs/handbook/unions-and-intersections.html#discriminating-unions). It simplifies narrowing polymorphic types.

2021-03-05 03:08 UTC, seniorquico commented on packages/web-app/src/modules/storefront/models/StorefrontHeroItemProps.ts
> +      }
Looks like a repeated element. Probably good for a refactor into a reusable type.

2021-03-05 20:50 UTC, merged