Added new AntiVirus Guides to Storybook
SaladTechnologies/salad-applications pull request #625
Opened 2021-02-11 19:40 UTC by scottcinatl

2021-02-16 00:12 UTC, seniorquico requested changes

2021-02-16 00:12 UTC, seniorquico commented on packages/web-app/src/modules/error-views/components/FallthroughAntiVirusErrorPage.tsx
> +    position: 'absolute',
Is there any way to make this responsive to the actual position of the widget? Other than us changing it's position in the Zendesk config, I wonder if the absolute positioning could also fail with different edge cases such as page zooming, non-default DPIs, and broken fonts?

2021-02-16 00:12 UTC, seniorquico commented on packages/web-app/src/modules/error-views/components/FallthroughAntiVirusErrorPage.tsx
> +const tooltipText =
This should be inline in the JSX.

2021-02-16 00:12 UTC, seniorquico commented on packages/web-app/src/modules/error-views/components/FallthroughAntiVirusErrorPage.tsx
> +    const webWidgetInterval = setInterval(function () {
Should this continue to run every second as an interval? Or should this be a one-time check using `setTimeout`?

2021-02-16 00:12 UTC, seniorquico commented on packages/web-app/src/modules/error-views/components/FallthroughAntiVirusErrorPage.tsx
> +      getWidgetDisplay()
This isn't cancelled when the component unmounts, and it may result in a `setState` call on an unmounted component.

2021-02-16 00:12 UTC, seniorquico commented on packages/web-app/src/modules/error-views/components/FallthroughAntiVirusErrorPage.tsx
> +            <ScrollableContent width={650}>
How does this fixed width respond to different window sizes? Why are we constraining it to this narrow width? Was this picked based on some other, existing layout size?

2021-02-16 00:12 UTC, seniorquico commented on packages/web-app/src/modules/error-views/components/FallthroughAntiVirusErrorPage.tsx
> +                    onClick={onViewArticle ? () => onViewArticle(article.id) : undefined}
Why would `onViewArticle` be `undefined`? What can the user do if it's `undefined`?

2021-02-16 00:12 UTC, seniorquico commented on packages/web-app/src/modules/error-views/components/FallthroughAntiVirusErrorPage.tsx
> +              Use a different Anti-Virus provided?{' '}
> Use a different Anti-Virus provided?

This doesn't sound correct. Should it be:

> Use a different Anti-Virus product?

Also, is it correct to capitalize anti-virus this way?

2021-02-16 00:12 UTC, seniorquico commented on packages/web-app/src/modules/error-views/components/FallthroughAntiVirusErrorPage.tsx
> +        {webWidgetShowing && (
What about a smoother animation to transition this in? It just feels odd to flash in a second or two after the page has already finished rendering.

2021-02-16 23:24 UTC, scottcinatl commented on packages/web-app/src/modules/error-views/components/FallthroughAntiVirusErrorPage.tsx
> +    zIndex: 3002,
When I was using the other overlay component, I was running into issues with the zIndex of our current Tooltip health icon. 
![Capture](https://user-images.githubusercontent.com/28833112/108134293-d1955080-706a-11eb-90ef-bfce9d7b4593.PNG).

So either way, I was having to change a zIndex somewhere. Maybe we could create a task to better handle our zIndex usage?

2021-02-16 23:28 UTC, scottcinatl commented on packages/web-app/src/modules/error-views/components/FallthroughAntiVirusErrorPage.tsx
> +  closeButton: {
Not sure these will be used in the future, but will flag it in codemark.

2021-02-17 05:28 UTC, scottcinatl commented on packages/web-app/src/modules/error-views/components/FallthroughAntiVirusErrorPage.tsx
> +            <ScrollableContent width={650}>
The size of the content was based off Figma design for this error page.

2021-02-17 05:50 UTC, scottcinatl commented on packages/web-app/src/components/ScrollableContent.tsx
> +import Scrollbars from 'react-custom-scrollbars'
Yes, this is already a dependency. We have a Scrollbars component that handles scroll for a whole page, whereas the ScrollableContent component I created creates a scrollable contained box.

2021-02-17 05:58 UTC, scottcinatl commented on packages/web-app/src/modules/error-views/components/FallthroughAntiVirusErrorPage.tsx
> +    position: 'absolute',
I couldn't find any clean way in the Zendesk WebWidget API to determine where the position of the widget is.

2021-02-17 19:19 UTC, seniorquico commented on packages/web-app/src/modules/error-views/components/FallthroughAntiVirusErrorPage.tsx
> +    zIndex: 3002,
Ok. Yes, we need to tackle this better. Explicitly managing z-indexes is always feels like a nightmare, has to be done globally across the app. Let's spin this out as a refactor task in the backlog, and it'll probably be something to include in the scope of the component library project.

2021-02-18 01:06 UTC, seniorquico requested changes

2021-02-18 01:06 UTC, seniorquico commented on packages/web-app/src/modules/error-views/components/NewAntiVirusErrorPage.tsx
> +export const AntiVirusErrorPage = withStyles(styles)(_AntiVirusErrorPage)
The file name should be `AntiVirusErrorPage`, to match the component name.

2021-02-18 16:35 UTC, seniorquico approved these changes

2021-02-18 16:36 UTC, merged