Updates anti-virus error page to show Help Center anti-virus guides
SaladTechnologies/salad-applications pull request #629
Opened 2021-02-19 23:10 UTC by scottcinatl

1. Adds system process information to `getMachineInfo` call
2. Updates anti-virus error page with Zendesk Help Center Guides

2021-02-20 02:29 UTC, seniorquico requested changes

2021-02-20 02:29 UTC, seniorquico commented on packages/web-app/src/modules/zendesk/Zendesk.ts
> +  public selectedAntiVirusGuide?: AntiVirusSoftware | string
🤔

2021-02-20 02:29 UTC, seniorquico commented on packages/web-app/src/modules/zendesk/utils.ts
> +  return title.split('How to Whitelist Salad in').pop()
Why are we doing this? As the comment points out... feels fragile.

2021-02-20 03:54 UTC, scottcinatl commented on packages/web-app/src/modules/zendesk/utils.ts
> +  return title.split('How to Whitelist Salad in').pop()
I was debating whether to get the title this way or just hard code the title's for each individual article. I went with the parsing of the title in case another article was added to the list it would still be captured.

I guess it depends on what is more likely to happen more often, the changing of the article names, or the addition of new ones?

2021-02-23 00:32 UTC, seniorquico requested changes

2021-02-23 00:32 UTC, seniorquico commented on packages/web-app/src/modules/machine/MachineStore.ts
> +        this.setAntiVirusSoftware(machineInfo.processes)
Move this logic & state to the Zendesk store.

2021-02-23 00:32 UTC, seniorquico commented on packages/web-app/src/modules/machine/MachineStore.ts
> +  setAntiVirusSoftware = (processes: SystemProcesses) => {
Move this to a static function, e.g. in the Zendesk utils module.

2021-02-24 04:42 UTC, seniorquico approved these changes

2021-02-24 04:42 UTC, seniorquico commented on packages/web-app/src/modules/zendesk/utils.ts
> +  dance: for (const process of processes.list) {
🤦‍♂️

2021-02-24 16:07 UTC, merged