Added async redemption error flow
SaladTechnologies/salad-applications pull request #651
Opened 2021-03-16 20:07 UTC by scottcinatl

2021-04-22 22:51 UTC, scottcinatl commented on packages/web-app/src/modules/reward/RewardStore.ts
> +            title: 'The reward price is incorrect.',
@seniorquico The copy for these error messages is being created by Keith, so these will change before being merged in.

2021-04-22 23:30 UTC, seniorquico requested changes

2021-04-22 23:30 UTC, seniorquico commented on packages/web-app/src/modules/reward/RewardStore.ts
> +        if (error.message === REQUIRES_MINECRAFT_USERNAME) {
We need to move away from messages to the unique codes. In the future, the messages may be localized.

2021-04-22 23:30 UTC, seniorquico commented on packages/web-app/src/modules/reward/RewardStore.ts
> +        } else if (error.status === 409 || error.response?.status === 409) {
Why the different pattern? Should the same be applied to the checks above? Seems odd that only the `409` status code would require this, no?

2021-04-22 23:30 UTC, seniorquico commented on packages/web-app/src/axiosFactory.ts
> +export const REDEMPTIONS_INVALID_PRICE = 'The client reward price is out of sync.'
These error messages seem superfluous. Are they being used anywhere? If you really need to pipe through a message on the error object, the problem details response contains a message property.

2021-04-22 23:30 UTC, seniorquico commented on packages/web-app/src/modules/reward/RewardStore.ts
> +import { REDEMPTIONS_INVALID_PRICE, REQUIRES_MINECRAFT_USERNAME } from '../../axiosFactory'
This doesn't feel right. The axios client shouldn't have business logic elements. The error type codes are redemption-specific, and they should be living in this module.

2021-04-22 23:30 UTC, seniorquico commented on packages/web-app/src/modules/reward/RewardStore.ts
> +    if (this.redemptionId === undefined) {
What if the last redemption _attempt_ was for a different reward? Should that automatically trigger creating a new redemption ID?

2021-04-26 21:03 UTC, seniorquico approved these changes

2021-04-26 21:03 UTC, merged