Throttles AV Error Page to only show once per session
SaladTechnologies/salad-applications pull request #652
Opened 2021-03-18 15:23 UTC by scottcinatl

2021-03-24 06:37 UTC, seniorquico requested changes

2021-03-24 06:37 UTC, seniorquico commented on packages/web-app/src/modules/salad-bowl/SaladBowlStore.ts
> +  }
This looks like a bad code smell... the Salad Bowl store is managing state that it doesn't even use or care about. It would be better if this flag was maintained in the UI store, and the UI store would need to react to the start/end of a mining session.

2021-03-24 06:37 UTC, seniorquico commented on packages/web-app/src/UIStore.ts
> +          if (!hasViewedAVErrorPage) {
First, it feels wasteful to send two events (`trackMiningError` and `trackErrorPageViewed`) at the same time. Can these not be condensed?

Second, why do we track the error page viewed when we _don't_ view the error page (i.e. `hasViewedAVErrorPage === true`)?

2021-03-24 23:22 UTC, scottcinatl commented on packages/web-app/src/UIStore.ts
> +          if (!hasViewedAVErrorPage) {
Just had a conversation with Eric about this and he is okay with having both events being fired for now.

2021-03-25 13:37 UTC, seniorquico approved these changes

2021-03-25 16:08 UTC, merged