Update start button
SaladTechnologies/salad-applications pull request #653
Opened 2021-03-19 04:39 UTC by scottcinatl

2021-03-23 00:05 UTC, seniorquico requested changes

2021-03-23 00:05 UTC, seniorquico commented on packages/web-app/src/modules/machine-views/components/StartButton.tsx
> +            [classes.buttonChopping]: status === MiningStatus.Running,
```ts
const isPrepping = status !== MiningStatus.Running && progress !== undefined
const label = isPrepping ? (status === MiningStatus.Installing ? MiningStatus.Installing : MiningStatus.Initializing) : status
```

2021-03-23 00:05 UTC, seniorquico commented on packages/web-app/src/modules/salad-bowl/SaladBowlStore.ts
> +        percentage += 0.25
Do not mutate the percentage. This should be derived/computed from the `runningTime`.

2021-03-23 00:05 UTC, seniorquico commented on packages/web-app/src/modules/salad-bowl/SaladBowlStore.ts
> +  private preppingProgressPercentage: number = 0
Remove this!

2021-03-23 03:52 UTC, scottcinatl commented on packages/web-app/src/modules/salad-bowl/SaladBowlStore.ts
> +  private preppingProgressPercentage: number = 0
I still need to store the state of the progress made during prepping rather than just reference the run time. Each second that passes during the prep time I need to update the delta in percentage being added to progress based on which time frame the run time falls under.  Having the stored progress state makes this easier to do. 

For example, between 10 seconds and 30 seconds of run time, we are jumping from 10% to 15%. During that time frame, we are applying a .25% change each second. Each time frame has different percentage applied per second.

2021-03-24 01:31 UTC, seniorquico requested changes

2021-03-24 01:31 UTC, seniorquico commented on packages/web-app/src/modules/machine-views/components/StartButton.tsx
> +    marginLeft: () => (Math.tan((skew * Math.PI) / 180) * buttonHeight) / 2,
The `skew` and `buttonHeight` are constants, and this should also be a constant value.

2021-03-24 01:31 UTC, seniorquico commented on packages/web-app/src/modules/salad-bowl/SaladBowlStore.ts
> +  private preppingProgressPercentage: number = 0
Let's remove this! ;-)

2021-03-24 20:18 UTC, seniorquico commented on packages/web-app/src/modules/machine-views/components/StartButton.tsx
> +const skew = 30
```ts
const skewedMarginLeft = (Math.tan((skew * Math.PI) / 180) * buttonHeight) / 2;
```

2021-03-26 13:44 UTC, seniorquico approved these changes
It's beautiful!

2021-03-26 17:49 UTC, seniorquico approved these changes

2021-03-26 17:50 UTC, merged