Added Android, Epic Games, and Nintendo platform icons
SaladTechnologies/salad-applications pull request #654
Opened 2021-03-23 17:10 UTC by scottcinatl

2021-03-24 01:25 UTC, seniorquico commented on packages/web-app/src/modules/reward-views/components/RewardInfoPanel.tsx
> +import nintendo from './assets/logos/nintendo.png'
Do we have standards on size/aspect ratio? Seems odd that these are all different.

2021-03-24 16:46 UTC, scottcinatl commented on packages/web-app/src/modules/reward-views/components/RewardInfoPanel.tsx
> +import nintendo from './assets/logos/nintendo.png'
I tried to put all three to 128 x 128, but the aspect ratio for epic games icons looks squished at that size, so that one is a little different.

2021-03-24 19:01 UTC, seniorquico requested changes
Please drop in the optimized assets and add a quick readme/note to callout the needed dimensions.

2021-03-25 00:27 UTC, seniorquico approved these changes

2021-03-25 15:55 UTC, merged