Remove Offerwall from App
SaladTechnologies/salad-applications pull request #669
Opened 2021-04-26 22:14 UTC by jpark799

Removed offerwall but still waiting on Arlo to provide revised images. 
`earning-overview.svg` and `how-salad-works-rewards.svg` need to be revised.

2021-04-28 19:45 UTC, seniorquico requested changes

2021-04-28 19:45 UTC, seniorquico commented on packages/web-app/src/modules/error-views/components/AntiVirusFirewallErrorPage.tsx
> +                              Your Firewall is blocking you from chopping. We'll keep testing other miners, but your
This isn't related to offerwalls. ;-)

It looks like this PRs going to get delayed based on business constraints... Should this change be pulled out into a separate PR?

2021-04-28 19:45 UTC, seniorquico commented on packages/web-app/src/modules/storefront-views/utils.ts
> -    {
Is this data blob for Storybook? If so-- we should move it out of this file. Doesn't make sense to mix mock data in with other application utilities.

2021-04-28 20:20 UTC, jpark799 commented on packages/web-app/src/modules/storefront-views/utils.ts
> -    {
yeah, that makes sense. i'll go ahead and pull this out of the PR. 

thanks

2021-04-30 20:52 UTC, seniorquico approved these changes

2021-04-30 20:56 UTC, merged