Added basic bonus page
SaladTechnologies/salad-applications pull request #689
Opened 2021-06-15 22:14 UTC by dsarfati

2021-06-15 22:35 UTC, seniorquico requested changes

2021-06-15 22:35 UTC, seniorquico commented on packages/web-app/src/modules/bonus/BonusStore.ts
> +      yield this.axios.post(`/api/v2/bonuses/${bonusId}/claim`)
On success, does it make sense to show a toast notification? The toast could even be cute wrt click handler... if it's a reward bonus, it could take you to the reward vault.

2021-06-15 22:35 UTC, seniorquico commented on packages/web-app/src/index.tsx
> +import './index.css'
This was sorted (probably something that VS Code did automatically). The order here is super important, and these should be put back to their original order.

2021-06-16 00:14 UTC, scottcinatl commented on packages/web-app/src/index.tsx
> +    <RawIntlProvider value={intl}>
@dsarfati Had to add the RawIntlProvider on my PR as well. I did mine in App.tsx. So maybe now that mine is already merged in you could catch up with my branch and remove the ThemeProvider and RawIntlProvider from the App file

2021-06-16 00:48 UTC, seniorquico commented on packages/web-app/src/modules/bonus/BonusStore.ts
> +      yield this.axios.post(`/api/v2/bonuses/${bonusId}/claim`)
Added a backlog task to review this.

2021-06-16 00:50 UTC, seniorquico approved these changes

2021-06-16 00:50 UTC, merged