Added logic that allows user to decide whether or not to replace current earning rate bonus
SaladTechnologies/salad-applications pull request #728
Opened 2021-07-06 20:20 UTC by scottcinatl

2021-07-09 18:38 UTC, seniorquico requested changes

2021-07-09 18:38 UTC, seniorquico commented on packages/web-app/src/modules/bonus/BonusStore.ts
> +          yield this.replaceCurrentEarningRatePrompt()
The promise doesn't get canceled if the component is unmounted prematurely (say another component kicks off a route change... the auth store "signs out" the user... Salad Bowl store pops open the AV or incompatible modals... etc.).

I'm not seeing the value of the promise here. It's an internal implementation detail of the store, and it appears to be complicating the flow. With a slight refactor (and no changes to the components at all!), this can be accomplished without the promise.

I think we should remove this, and wait to introduce it when we have a legit, shared dialog manager component. In that scenario, I see the promise being a cross-store communication method.

2021-07-12 17:56 UTC, scottcinatl commented on packages/web-app/src/modules/bonus/BonusStore.ts
> +          yield this.replaceCurrentEarningRatePrompt()
@seniorquico Removed the promise-based replacement flow

2021-07-12 19:09 UTC, seniorquico approved these changes

2021-07-12 19:10 UTC, merged