Carousel Scroll for Levels
SaladTechnologies/salad-applications pull request #735
Opened 2021-07-12 21:42 UTC by jpark799

[React-Multi-Carousel](https://github.com/YIZHUANG/react-multi-carousel/issues/150) unfortunately does not allow you to start at a non-zero index so I had to reorder the array to have the current level be the first item.

2021-07-13 15:43 UTC, dsarfati requested changes
Are those the default arrows? Is there an issue using the same arrows we use for the reward list?

2021-07-13 15:43 UTC, dsarfati commented on packages/web-app/src/modules/seasons-views/pages/CurrentSeasonPage.tsx
> +  nextLevel >= 2 && levelCards.push(...levelCards.splice(0, nextLevel - 1))
What does this code do?? Is this moving the cards around?

2021-07-13 21:18 UTC, jpark799 commented on packages/web-app/src/modules/seasons-views/pages/CurrentSeasonPage.tsx
> +  nextLevel >= 2 && levelCards.push(...levelCards.splice(0, nextLevel - 1))
yeah, it's moving the current level to the front of the array and moving everything before the current array to the back of the array

2021-07-14 13:04 UTC, jpark799 commented
![image](https://user-images.githubusercontent.com/37646831/125626783-d97ab596-e9bc-415e-8f2d-c359bd3c6f67.png)

2021-07-14 13:10 UTC, dsarfati approved these changes

2021-07-14 13:13 UTC, merged