Onboarding 1 Revamp
SaladTechnologies/salad-applications pull request #744
Opened 2021-07-28 13:44 UTC by jpark799

First phase of Onboarding update

2021-07-30 21:15 UTC, jpark799 commented on packages/web-app/src/modules/referral/ReferralStore.ts
> +  submitReferralCodeOnboarding = flow(function* (this: ReferralStore, code: string) {
`submitReferralCode` is being used in the account page so in order to track only the referral codes being submitted in the onboarding process, I made a new function called `submitReferralCodeOnboarding` and renamed `submitDefaultReferralCode` to submitDefaultReferralCodeOnboarding` to be more specific

2021-07-30 21:55 UTC, scottcinatl commented on packages/web-app/src/modules/analytics/AnalyticsStore.ts
> +  /** Track when a button is clicked */ // use this for button clicks
You could remove this added comment.

2021-07-30 21:59 UTC, seniorquico requested changes

2021-07-30 21:59 UTC, seniorquico commented on packages/web-app/src/index.tsx
> +if (!rootStore.auth.isAuthenticated) {
Upfront login is required when running in Electron. However, login may be deferred when running in a web browser.

2021-07-30 21:59 UTC, seniorquico commented on packages/web-app/src/modules/analytics/AnalyticsStore.ts
> +  }
Remove this. The backend already pushes this event.

2021-07-30 22:00 UTC, scottcinatl commented on packages/web-app/src/modules/referral/ReferralStore.ts
> +        this.store.analytics.trackOnboardingPageViewed('Onboarding Welcome', 1) // pass username through?
You could also remove the comment here

2021-08-01 03:38 UTC, jpark799 commented on packages/web-app/src/index.tsx
> +if (!rootStore.auth.isAuthenticated) {
oh that's a great point. thank you for catching that

2021-08-01 03:56 UTC, jpark799 commented on packages/web-app/src/index.tsx
> +if (!rootStore.auth.isAuthenticated) {
i'm doing a `if (window.salad.platform !== 'web' && !rootStore.auth.isAuthenticated)` to make sure we're not in a web browser. if there's another preferred way to do this check, please let me know but i just tested and it's working as we need.

2021-08-02 15:27 UTC, scottcinatl commented on packages/web-app/src/index.tsx
> +if (!rootStore.auth.isAuthenticated) {
Instead of `.window.salad.platform !== 'web'`, we already have a check to see if the user is on the desktop app with `this.store.native.isNative`

2021-08-02 15:48 UTC, jpark799 commented on packages/web-app/src/index.tsx
> +if (!rootStore.auth.isAuthenticated) {
@scottcinatl oh awesome. thank you for letting me know.

2021-08-02 16:32 UTC, seniorquico commented on packages/web-app/src/index.tsx
> +if (rootStore.native.isNative && !rootStore.auth.isAuthenticated) {
If I recall correctly, `isAuthenticated` is determined _asynchronously_ (it may require an API call to refresh the access token). How does routing to `/login` work after the `isAuthenticated` flag is set to `true`?

2021-08-02 19:30 UTC, jpark799 commented on packages/web-app/src/index.tsx
> +if (rootStore.native.isNative && !rootStore.auth.isAuthenticated) {
I'm just doing a `rootStore.routing.replace('/login')` to set the route to the login page. I did some digging through the codebase and saw this is how we're doing it in a number of places. If there's another way to do routing that you would prefer, please let me know and I'd be happy to make an update.

2021-08-06 16:37 UTC, seniorquico requested changes

2021-08-06 16:37 UTC, seniorquico commented on packages/web-app/src/Store.ts
> +  public appLoaded: boolean = true
Rename to `appLoading`.

2021-08-06 16:37 UTC, seniorquico commented on packages/web-app/src/index.tsx
> +import { DefaultTheme as EmotionTheme, LoadingScreen } from '@saladtechnologies/garden-components'
The build failed because the new garden package was updated correctly:

- The old `tgz` file should be deleted.
- The `package.json` file should be updated to reference the new version.
- The `yarn.lock` file should be updated to reference the new version.

2021-08-06 17:18 UTC, seniorquico submitted a review, later dismissed

2021-08-06 18:52 UTC, seniorquico approved these changes

2021-08-06 19:55 UTC, merged