Add Disable Sleep Mode Function
SaladTechnologies/salad-applications pull request #765
Opened 2021-08-18 15:55 UTC by jpark799

This PR adds the ability to enable sleep mode on all the user's power profiles. We will still need to wire this up to the frontend.

2021-08-19 06:23 UTC, seniorquico requested changes

2021-08-19 06:23 UTC, seniorquico commented on packages/desktop-app/src/main.ts
> +  bridge.on('disable-sleep-mode', () => {
The comment above this doesn't look right.

2021-08-19 06:23 UTC, seniorquico commented on packages/desktop-app/src/main.ts
> +    const powercfg = 'C:\\Windows\\System32\\powercfg.exe'
We should add a check to guard against running this on macOS/Linux platforms.

2021-08-19 06:23 UTC, seniorquico commented on packages/web-app/src/modules/machine/NativeStore.ts
> +  disableSleepMode = (): Promise<void> => {
We should add a check to guard against running this on macOS/Linux platforms.

2021-08-19 06:23 UTC, seniorquico commented on packages/web-app/src/modules/machine/NativeStore.ts
> +  }
We may want to consider adding a `canDisableSleepMode` property. That would be computed using the current platform & the version of the native bridge interface. The onboarding business logic would use this to know if the sleep mode page should be shown or automatically skipped when unsupported.

2021-08-19 22:11 UTC, jpark799 commented on packages/web-app/src/modules/machine/NativeStore.ts
> +  }
by version of the native bridge interface, do you mean to just make sure the desktop version is greater than 13.1.2(current version) or would the api version also work(currently 8)?

2021-08-23 22:01 UTC, seniorquico requested changes

2021-08-23 22:01 UTC, seniorquico commented on packages/web-app/src/modules/machine/NativeStore.ts
> +              reject()
The `reject`s below return a message. Should this also return a generic error message? Something to the effect of "try again" and "if it keeps failing, contact support"?

2021-08-23 22:01 UTC, seniorquico commented on packages/desktop-app/src/main.ts
> +                `${powercfg} /setacvalueindex ${profile[1]} 238c9fa8-0aad-41ed-83f4-97be242c8f20 29f6c1db-86da-48c5-9fdb-f2b67b1f44da 0`,
Add comment(s) to describe what each of these magic GUIDs stands for.

2021-08-24 00:42 UTC, seniorquico approved these changes

2021-08-24 13:53 UTC, merged