Add Whitelist Windows Defender Function
SaladTechnologies/salad-applications pull request #766
Opened 2021-08-19 03:05 UTC by jpark799

This PR adds the ability to whitelist windows defender. We will still need to wire this up to the frontend but the function calls and script is all there now.

2021-08-19 03:09 UTC, jpark799 commented on packages/desktop-app/src/main.ts
> +          const phrase = /The operation was canceled by the user./
We print off `The operation was canceled by the user` in the error message when users select no after being prompted by the elevated command. I'm just using regex to see if this phrase is in the error message and if not, we can safely assume that there was caused by the script.

2021-08-19 03:14 UTC, jpark799 commented on packages/desktop-app/src/models/WhitelistWindowsDefenderErrorType.ts
> +export enum WHITELIST_WINDOWS_DEFENDER_ERROR_TYPE {
i saw we were doing screaming snake case in some places and just pascal case with naming our enums. i went with screaming snake case but if there's another pattern you would prefer, i can update this

2021-08-19 03:16 UTC, jpark799 commented on packages/desktop-app/src/models/WhitelistWindowsDefenderErrorType.ts
> +  GENERAL_SCRIPT_ERROR = 'General Script Error',
not super crazy about these error type names. if there's something that you think would fit better, i'm all ears.

2021-08-19 06:25 UTC, seniorquico commented on packages/desktop-app/src/main.ts
> +          const phrase = /The operation was canceled by the user./
The problem with the RegExp is that this message will be localized when Windows is set to use a different language. We should use the `error.code` property instead.

Testing & observing return values from various use cases will be the quickest way to identify what we're looking for. Microsoft documents all of the system error codes here:

https://docs.microsoft.com/en-us/windows/win32/debug/system-error-codes

2021-08-19 16:15 UTC, jpark799 commented on packages/desktop-app/src/main.ts
> +          const phrase = /The operation was canceled by the user./
yeah, i thought about this too after our conversation around localized machines. unfortunately, clicking no on the prompt registers as an error code 1 which just means incorrect function. it doesn't look like there's a specific error code for when a user clicks no. running an invalid script, also prints off a code 1 so we wouldn't have a way to differentiate between a user clicking no and just a general error. the only difference i could find was the errormessage actually prints off ` This command cannot be run due to the error: The operation was canceled by the user.`

2021-08-24 00:41 UTC, seniorquico requested changes

2021-08-24 00:41 UTC, seniorquico commented on packages/desktop-app/src/main.ts
> +          console.error(`Failed to Whitelist Windows Defender: ${error.message}`)
```suggestion
      (error, _stdout, stderr) => {
        if (error) {
          console.error(`Failed to Whitelist Windows Defender (${error.message}${error.code == null ? '' : `, exit code ${error.code}`})${stderr ? `\n${stderr}` : ''}`)
```

2021-08-24 00:41 UTC, seniorquico commented on packages/desktop-app/src/main.ts
> +            : `${process.env.APPDATA}\\Salad\\plugin-bin`,
If it isn't already, import the `path` module and use the `join` function.

```suggestion
            ? path.join(nonDefaultFilePath, 'Salad/plugin-bin')
            : path.join(process.env.APPDATA, 'Salad/plugin-bin'),
```

2021-08-24 19:14 UTC, jpark799 commented on packages/desktop-app/src/main.ts
> +      'PowerShell.exe -NoLogo -NoProfile -NonInteractive -WindowStyle Hidden -EncodedCommand WwBTAHkAcwB0AGUAbQAuAFQAZQB4AHQALgBFAG4AYwBvAGQAaQBuAGcAXQA6ADoAVQBUAEYAOAAuAEcAZQB0AFMAdAByAGkAbgBnACgAWw
is there a reason you want it to be `index.js` and not `index.ts`?

2021-08-24 19:54 UTC, jpark799 commented on packages/desktop-app/src/main.ts
> +      'PowerShell.exe -NoLogo -NoProfile -NonInteractive -WindowStyle Hidden -EncodedCommand WwBTAHkAcwB0AGUAbQAuAFQAZQB4AHQALgBFAG4AYwBvAGQAaQBuAGcAXQA6ADoAVQBUAEYAOAAuAEcAZQB0AFMAdAByAGkAbgBnACgAWw
putting the index file as a `.ts` because i was getting this error. 

```  ERROR in undefined(undefined,undefined):
  TS5055: Cannot write file 'C:/Users/jason/Documents/Coding Applications/salad-applications/packages/desktop-app/src/whitelistWindowsScript/index.js' because it would overwrite input file.```

2021-08-24 22:43 UTC, jpark799 commented on packages/desktop-app/src/main.ts
> +            : `${process.env.APPDATA}\\Salad\\plugin-bin`,
`process.env.APPDATA` is possibly undefined so we aren't able to use the `path.join`. i can have this default to something else if proces.env.APPDATA is undefined but what should i default it to?

2021-08-25 01:38 UTC, seniorquico commented on packages/desktop-app/src/main.ts
> +            : `${process.env.APPDATA}\\Salad\\plugin-bin`,
It's technically possible to have an undefined APPDATA environment variable, although incredibly unlikely. You could handle it... if it's not defined, you can push an error to the web side.

2021-08-25 14:18 UTC, seniorquico requested changes

2021-08-25 14:18 UTC, seniorquico commented on packages/desktop-app/src/main.ts
> +            ? path.join(nonDefaultFilePath, 'Salad/plugin-bin')
```suggestion
            ? path.normalize(filePath)
```

We should take the full file path from the caller. This will give us more flexibility, and can be used in the very near future with Salad Bowl's new folder paths (which won't have `plugin-bin` in the path).

2021-08-28 04:31 UTC, seniorquico approved these changes

2021-08-28 05:49 UTC, merged