Adds Sleep-Mode and Auto-Start pages to onboarding flow
SaladTechnologies/salad-applications pull request #772
Opened 2021-08-27 20:12 UTC by jpark799

2021-08-30 20:33 UTC, scottcinatl approved these changes

2021-08-31 14:17 UTC, seniorquico requested changes

2021-08-31 14:17 UTC, seniorquico commented on packages/desktop-app/src/preload.js
> +    apiVersion: 8,
Why is this being rolled back?

2021-09-01 14:10 UTC, jpark799 commented on packages/desktop-app/src/preload.js
> +    apiVersion: 8,
because we didn't have the latest desktop app published yet and we were using this as a flag to know if we should show the sleepmode pages. given that we've published the latest version of desktop, this can be 9 now.

2021-09-02 17:46 UTC, scottcinatl approved these changes

2021-09-02 18:26 UTC, merged