Antivirus 2 second wait
SaladTechnologies/salad-applications pull request #787
Opened 2021-09-03 21:26 UTC by jpark799

We're now waiting 2 seconds after successfully whitelisting windows defender to show the success toast notification and push users to the store. Also updated one of the error messages

2021-09-04 01:12 UTC, seniorquico requested changes

2021-09-04 01:12 UTC, seniorquico commented on packages/web-app/src/modules/onboarding/OnboardingAntivirusStore.tsx
> +      setTimeout(() => {
This breaks out of the flow. The delay should instead be part of it.

2021-09-04 01:12 UTC, seniorquico commented on packages/web-app/src/modules/onboarding/models/WhitelistWindowsDefenderErrorType.ts
> +  USER_SELECTED_NO = `You need to click 'Yes' on the User Account Control Prompt to whitelist Windows Defender. Please try again.`,
It seems weird that our long-form messages are our enum values.

2021-09-07 16:13 UTC, Vukkyy commented on packages/web-app/src/modules/onboarding/models/WhitelistWindowsDefenderErrorTypeMessage.ts
> +  USER_SELECTED_NO = `You need to click 'Yes' on the User Account Control Prompt to whitelist Windows Defender. Please try again.`,
whitelist... Windows Defender? I feel like this kind of implies you're whitelisting the Windows Defender application instead of whitelisting Salad (from what I've seen, it's referred to as "whitelisting Salad" everywhere else)

2021-09-07 16:23 UTC, jpark799 commented on packages/web-app/src/modules/onboarding/models/WhitelistWindowsDefenderErrorType.ts
> +  USER_SELECTED_NO = `You need to click 'Yes' on the User Account Control Prompt to whitelist Windows Defender. Please try again.`,
i renamed WhitelistWindowsDefenderErrorType to WhitelistWindowsDefenderErrorTypeMessage to be more accurate.

2021-09-08 22:07 UTC, jpark799 commented on packages/web-app/src/modules/onboarding/models/WhitelistWindowsDefenderErrorTypeMessage.ts
> +  USER_SELECTED_NO = `You need to click 'Yes' on the User Account Control Prompt to whitelist Windows Defender. Please try again.`,
thank you for the feedback, @Vukkyy. I've gone ahead and updated the error message.

2021-09-08 23:05 UTC, seniorquico approved these changes

2021-09-09 01:30 UTC, merged