Show Autostart Page if Autostart Not Enabled
SaladTechnologies/salad-applications pull request #789
Opened 2021-09-09 19:28 UTC by jpark799

2021-09-09 22:13 UTC, jpark799 commented on packages/web-app/src/modules/onboarding/OnboardingStore.tsx
> +  public get hasCompletedOnboarding(): boolean {
rename to hasCompletedAvailableOnboardingPages

2021-09-09 22:14 UTC, jpark799 commented on packages/web-app/src/modules/onboarding/OnboardingStore.tsx
> +      this.availableOnboardingPages.length <= JSON.parse(this.onboardingPagesCompleted).length
do an exact check here instead of just checking the length

2021-09-09 22:14 UTC, jpark799 commented on packages/web-app/src/modules/onboarding/OnboardingAutoStartStore.tsx
> +  public get haveSeenAutoStartPage(): boolean {
renamed to hasSeenAutoStartPage

2021-09-10 16:07 UTC, scottcinatl requested changes

2021-09-10 16:07 UTC, scottcinatl commented on packages/web-app/src/Store.ts
> +      if (this.onboardingAutoStart.shouldShowAutoStartPageAgain) {
We will most likely be adding more of these little nudges to change a setting that was previously set in onboarding. So it might be helpful to provide a more generic pattern for showing these pages to the user.

2021-09-10 16:07 UTC, scottcinatl commented on packages/web-app/src/modules/onboarding-views/pages/AutoStartConfigurationPage.tsx
> +  isDoNotShowAutoStartAgainChecked: boolean
nit: change `isDoNotShowAutoStartAgainChecked` to `doNotShowAutoStartAgain`

2021-09-10 16:07 UTC, scottcinatl commented on packages/web-app/src/modules/onboarding-views/pages/AutoStartConfigurationPage.tsx
> +            {haveSeenAutoStartPage && (
nit: change `haveSeenAutoStartPage` to `hasSeenAutoStartPage`

2021-09-10 16:07 UTC, scottcinatl commented on packages/web-app/src/modules/onboarding/OnboardingAutoStartStore.tsx
> +    if (Storage.getItem(DO_NOT_SHOW_AUTO_START_AGAIN)) {
I believe this storage method returns a string. If we are wanting to return a boolean based on the storage item value, we should probably be more explicit about what we determing as the right condition for `true`.

2021-09-10 16:07 UTC, scottcinatl commented on packages/web-app/src/modules/onboarding/OnboardingAutoStartStore.tsx
> +      this.store.onboarding.viewNextPage(ONBOARDING_PAGE_NAMES.AUTO_START_CONFIGURATION)
We shouldn't be mixing the action of changing a user's settings with a routing decision. There should be a separate action that calls `enableAutoStart` and then provide whatever other functionality desired after, in this case, a routing action.

2021-09-13 19:53 UTC, scottcinatl approved these changes

2021-09-13 20:04 UTC, merged