Updates Antivirus Modal
SaladTechnologies/salad-applications pull request #804
Opened 2021-10-01 15:27 UTC by jpark799

Updates our antivirus modal to use our garden modal

2021-10-01 17:03 UTC, scottcinatl requested changes

2021-10-01 17:03 UTC, scottcinatl commented on packages/web-app/src/modules/onboarding/OnboardingAntivirusStore.tsx
> +  public onViewAVArticleWithId = (id: string) => {
Now if you want to better distinguish these store function calls within the store by `id` or `string` in the name because you can't have `onViewAVArticle` twice, I think that is fine. But, the props for the components doesn't need to change. The types for the arguments being passed handle what is needed on the component side.

2021-10-01 18:43 UTC, jpark799 commented on packages/web-app/src/modules/onboarding-views/models/AntivirusInfo.ts
> +export const antivirusInfo = [
yeah, probably not. i'll remove the models folder and just place this where the containers are

2021-10-01 18:46 UTC, scottcinatl commented on packages/web-app/src/modules/onboarding-views/models/AntivirusInfo.ts
> +export const antivirusInfo = [
I think it would be good to still have it in a separate file, just not under models.

2021-10-01 18:50 UTC, jpark799 commented on packages/web-app/src/modules/onboarding-views/pages/SleepModeConfigurationPage.tsx
> +    width: 180,
the button is responsive but it's new lining like the button on the autostart onboarding page was. changing the width to 180 makes sure the text is all on one line. 

![image](https://user-images.githubusercontent.com/37646831/135671793-3690e990-9b6f-49ab-b8a2-ab2e16c3975d.png)

2021-10-01 20:00 UTC, jpark799 commented on packages/web-app/src/modules/onboarding-views/models/AntivirusInfo.ts
> +export const antivirusInfo = [
i originally left the file as is and moved it to the `onboarding-views` folder. now that i think about it, i think the `utils.ts` file under the zendesk folder can absorb all this. all the AV info is already stored there so i think that's the right place for this.

2021-10-05 18:57 UTC, scottcinatl requested changes

2021-10-05 18:57 UTC, scottcinatl commented on packages/web-app/src/modules/onboarding-views/pages/AntivirusConfigurationPage.tsx
> +          <AntivirusModal navigateToAVGuide={navigateToAVGuide} onNoAVClick={onNoAVClick} />
I think the naming of this component could be confusing. At a glance it looks like we have a Modal with another Modal as it's child. I would change `AntivirusModal` to `AntivirusModalContent` or something like that to make it more clear.

2021-10-05 18:57 UTC, scottcinatl commented on packages/web-app/src/modules/onboarding-views/pages/SleepModeConfigurationPage.tsx
> +              <span>
Now that there are no styles applied to the `span`, what value does it provide?

2021-10-05 18:57 UTC, scottcinatl commented on packages/web-app/src/modules/onboarding-views/components/AntivirusModal.tsx
> +const _AntivirusModal = ({ classes, navigateToAVGuide, onNoAVClick }: AntivirusModalProps) => {
Shouldn't we have two possible types of content showing in the new Modal. I know the designs only showcase the list of different AVs to select from, but once the user clicks on the specific AV Guide, shouldn't the modal then show the specific AV guide information retrieved from Zendesk. Might want to ping Eric on that flow.

2021-10-06 15:47 UTC, merged