install saladbowl and saladbowl runner
SaladTechnologies/salad-applications pull request #853
Opened 2022-01-10 16:14 UTC by thesaladmander

Updates the installer to install the Salad.Bootstrapper into Salad/SaladBowl and the previous SaladBowl into Salad/SaladBowlRunner.  I also update the appsettings file for the bootstrapper to point to the installed SaladBowlRunner/Salad.Bowl.Service.exe.  So the appsettings file is assumed to have an SBExe and SBDir in the configuration to be replaced by the appropriate location for the runner.

The result is that the installer should run 'SaladBowl' (now referencing Salad.Boostrapper) on Session 0 which will run SaladBowlRunner on Session 1 (or something non-0).

Kyle: I removed the underscores on the install files.  Did you want me to check those in that way or not?

2022-01-25 01:33 UTC, seniorquico requested changes

2022-01-25 01:33 UTC, seniorquico commented on packages/desktop-app/build/salad-bowl/_install.nsh
> +!insertmacro _ReplaceInFile "$INSTDIR\SaladBowl\appsettings.json" "SBEXE" "$7\\SaladBowlRunner\\Salad.Bowl.Service.exe"
Let's move the path to `Salad.Bowl.Service.exe` to the service's command line arguments.

2022-01-26 19:22 UTC, seniorquico requested changes

2022-01-26 19:22 UTC, seniorquico commented on packages/desktop-app/build/salad-bowl/_install.nsh
> +  SimpleSC::InstallService "SaladBowl" "Salad Bowl" "16" "2" "$INSTDIR\SaladBowl\Salad.Bootstrapper.exe" "" "" ""
According to the [SimpleSC docs](https://nsis.sourceforge.io/NSIS_Simple_Service_Plugin), the binary path should include the arguments. I also think we need to explicitly quote them to cover potential spaces in the `$INSTDIR` path.

```suggestion
  SimpleSC::InstallService "SaladBowl" "Salad Bowl" "16" "2" "$INSTDIR\SaladBowl\Salad.Bootstrapper.exe --sb $\"$INSTDIR\SaladBowlRunner\Salad.Bowl.Service.exe$\"" "" "" ""
```

2022-01-26 19:22 UTC, seniorquico commented on packages/desktop-app/build/salad-bowl/_install.nsh
> +  SimpleSC::StartService "SaladBowl" "--sb $INSTDIR\SaladBowlRunner\Salad.Bowl.Service.exe" 30
If the argument is baked into the service installation, then this may be unnecessary?

2022-01-27 18:33 UTC, thesaladmander commented on packages/desktop-app/build/salad-bowl/_install.nsh
> +  SimpleSC::StartService "SaladBowl" "--sb $INSTDIR\SaladBowlRunner\Salad.Bowl.Service.exe" 30
yeah, this wasn't working.  I did test it, but I screwed up the test.  So the trick as you'll see is the whole string needs to be in single quotes and inside you can use double quotes.  Tried the reverse initially and it didn't work.  I tried your escapes and it didn't compile.

2022-01-27 21:48 UTC, seniorquico approved these changes

2022-01-27 21:49 UTC, merged