[Bug] broken Auto Start link
SaladTechnologies/salad-applications pull request #860
Opened 2022-01-24 21:07 UTC by jpark799

we had a link to the desktop settings page that would always show even in the webapp. this page wasn't accessible though unless you were in the desktop app so i added a check to see if we're in the native app. the path has also changed so i updated it. 
![image](https://user-images.githubusercontent.com/37646831/150864900-0e2a82b4-2419-49c1-806b-ebc1613161ce.png)

2022-01-24 21:46 UTC, scottcinatl requested changes
Does a similar change need to be made in the alpha branch as well? To at least remove the link when the user is on the browser instead of the desktop app?

2022-01-24 21:46 UTC, scottcinatl commented on packages/web-app/src/modules/earn-views/components/MiningInformation.tsx
> +                <b>
I would remove the blank spaces from your `Auto Start` text block that doesn't include the link. 

nit: you could just use the ternary inside the the html tag. 

```
  <b>
       {isNative ? <SmartLink to="/account/desktop-settings">Auto Start</SmartLink> : "Auto Start"}
  </b>
```

2022-01-25 00:25 UTC, jpark799 commented on packages/web-app/src/modules/earn-views/components/MiningInformation.tsx
> +                <b>
yeah, we're going to need to make the change to the alpha project as well. once this PR is approved, i can make the change in that branch.

great call on making the ternary less messy. i like that way more and i'll get that implemented.

2022-01-25 01:31 UTC, seniorquico approved these changes

2022-01-25 17:10 UTC, merged