Loading Helpscout AV articles
SaladTechnologies/salad-applications pull request #902
Opened 2022-03-15 22:13 UTC by jpark799

the onboarding pages will be the same but in our alpha branch, we are using the `error/` routes. of the error routes, only the three below were pulling from zendesk

**- `/errors/anti-virus/:id`**
![image](https://user-images.githubusercontent.com/37646831/158480726-a82fecab-e915-4541-85ae-fa74701b6857.png)
![image](https://user-images.githubusercontent.com/37646831/158480821-1b3b95b2-393e-4e85-aa2a-0d01546067b1.png)
clicking the link will bring us to the generic antivirus route.
![av gif2](https://user-images.githubusercontent.com/37646831/158480994-b5f08db3-e699-49c6-a005-dfd353e9ea7e.gif)

**- `/errors/anti-virus/`** 
![image](https://user-images.githubusercontent.com/37646831/158480631-7d357120-3ab9-471c-8656-989f7cbec2c3.png)

**- `/errors/firewall`**
![image](https://user-images.githubusercontent.com/37646831/158481089-41499b7d-a51a-411d-88ea-0983b1ab8ce6.png)

2022-03-15 23:06 UTC, scottcinatl requested changes

2022-03-15 23:06 UTC, scottcinatl commented on packages/web-app/src/modules/error-views/components/AntiVirusFirewallErrorPage.tsx
> -      onViewArticle,
This action to view article didn't just navigate a user to the correct page, it also had business logic that tracked which article a user clicked on for mixpanel. So these clicks should be captured just as they were before.

2022-03-15 23:06 UTC, scottcinatl commented on packages/web-app/src/modules/error-views/components/AntiVirusFirewallErrorPage.tsx
> -      article,
If we are removing props from being needed, I would expect that their would be changes made in the container components as well that passes down those props.

2022-03-16 19:15 UTC, jpark799 commented
new general AV page. 
![image](https://user-images.githubusercontent.com/37646831/158669798-3092ced5-3c49-4b60-97da-0a948135b72d.png)

2022-03-16 19:47 UTC, scottcinatl approved these changes

2022-03-16 19:48 UTC, merged