[App] Adding redirect_uri on login page
SaladTechnologies/salad-applications pull request #912
Opened 2022-04-28 17:23 UTC by jpark799

if you click on any of the login buttons in the app, we will pass the path to the `redirect_uri` which will redirect you back to the page after authenticating.

2022-04-28 17:25 UTC, seniorquico requested changes

2022-04-28 17:25 UTC, seniorquico commented on packages/web-app/src/modules/auth/AuthStore.ts
> +        this.router.replace(`/login/?redirect_uri=${path}`)
But this will navigate to the app's _internal_ login page. That page doesn't support `redirect_uri`. We'd need to intercept `/login` navigation events and explicitly push them to the _external_ login app.

2022-04-28 17:32 UTC, scottcinatl requested changes

2022-04-28 17:32 UTC, scottcinatl commented on packages/web-app/src/modules/auth/AuthStore.ts
>        this.startingRoute = this.router.location.pathname === '/login' ? '/store' : this.router.location.pathname
Is `startingRoute` relevant anymore? If Login is now handling the redirect?

2022-04-28 20:33 UTC, jpark799 commented on packages/web-app/src/modules/auth/AuthStore.ts
>        this.startingRoute = this.router.location.pathname === '/login' ? '/store' : this.router.location.pathname
oh great catch. i guess it isn't

2022-04-28 20:56 UTC, jpark799 commented on packages/web-app/src/modules/auth/AuthStore.ts
> +        this.router.replace(`/login/?redirect_uri=${path}`)
aw actually `window.location.replace` should work. lmk if there's another method that you would prefer though

2022-04-28 23:27 UTC, seniorquico commented on packages/web-app/src/modules/auth/AuthStore.ts
> +        this.router.replace(`/login/?redirect_uri=${path}`)
Hard-coding it to `salad.com` will break non-production environments, though. It's best if it's kept as an absolute _path_ (i.e. `/login?redirect_uri=...`). You just need to explicitly break out of React Router navigation and let the browser leave/go to the new login app.

2022-05-03 01:12 UTC, seniorquico approved these changes

2022-05-03 01:21 UTC, merged