Remove zendesk references
SaladTechnologies/salad-applications pull request #942
Opened 2022-08-23 00:10 UTC by jpark799

removes all references to zendesk.

2022-08-23 00:17 UTC, seniorquico requested changes
This removes the Help Scout beacon. We need to keep this.

2022-08-23 01:11 UTC, seniorquico requested changes

2022-08-23 01:11 UTC, seniorquico commented on packages/web-app/src/modules/error-views/FallbackErrorContainer.ts
> -    onOpenSupportTicket: () => store.zendesk.openSupportTicket(),
Shouldn't we still open the Help Scout beacon here?

2022-08-23 01:11 UTC, seniorquico commented on packages/web-app/src/modules/error-views/components/FallbackErrorPage.tsx
> -  onOpenSupportTicket: () => void
Shouldn't we still open the Help Scout beacon here?

2022-08-23 01:11 UTC, seniorquico commented on packages/web-app/src/modules/helpscout/models/HelpScout.tsx
> +    }
Is this now defined twice? It probably shouldn't be part of the Help Scout types.

2022-08-23 01:11 UTC, seniorquico commented on packages/web-app/src/modules/machine-views/DontLoseProgressContainer.ts
> -  onSubmitSupportTicket: () => store.zendesk.openSupportTicket(),
Shouldn't we still open the Help Scout beacon here?

2022-08-23 01:11 UTC, seniorquico commented on packages/web-app/src/modules/machine-views/components/DontLoseProgress.tsx
> -  onSubmitSupportTicket: () => void
Shouldn't we still open the Help Scout beacon here?

2022-08-23 01:11 UTC, seniorquico commented on packages/web-app/src/modules/start-button/StartButtonUIStore.tsx
> -        this.store.zendesk.openSupportTicket()
Shouldn't we still open the Help Scout beacon here?

2022-08-23 01:11 UTC, seniorquico commented on packages/web-app/src/modules/onboarding-views/OnboardingSpecificAntivirusGuideContainer.tsx
> -import { getSanitizedHTML } from '../../utils'
It looks like we've removed a lot of references to this `getSanitizedHTML` function. Is it still being used in the app, or should it also be removed?

2022-08-23 14:20 UTC, jpark799 commented on packages/web-app/src/modules/helpscout/models/HelpScout.tsx
> +    }
it's only defined once. it was original in a model file under zendesk but i removed all those. i'll move this to an onboarding models file because we're using it in the onboarding

2022-08-23 15:11 UTC, jpark799 commented on packages/web-app/src/modules/machine-views/DontLoseProgressContainer.ts
> -  onSubmitSupportTicket: () => store.zendesk.openSupportTicket(),
the help scout beacon will still be there but because of the z-index being 2000 on the `DontLoseProgress` page and `FallBackErrorPage` it isn't viewable. given that this is in the legacy app, i don't know if it's worth the effort to rework these. i did add links to the support page though.

2022-08-23 15:11 UTC, jpark799 commented on packages/web-app/src/modules/error-views/components/FallbackErrorPage.tsx
> -  onOpenSupportTicket: () => void
the help scout beacon will still be there but because of the z-index being 2000 on the `DontLoseProgress` page and `FallBackErrorPage` it isn't viewable. given that this is in the legacy app, i don't know if it's worth the effort to rework these. i did add links to the support page though.

2022-08-23 15:11 UTC, jpark799 commented on packages/web-app/src/modules/error-views/FallbackErrorContainer.ts
> -    onOpenSupportTicket: () => store.zendesk.openSupportTicket(),
the help scout beacon will still be there but because of the z-index being 2000 on the `DontLoseProgress` page and `FallBackErrorPage` it isn't viewable. given that this is in the legacy app, i don't know if it's worth the effort to rework these. i did add links to the support page though.

2022-08-23 15:17 UTC, jpark799 commented on packages/web-app/src/modules/start-button/StartButtonUIStore.tsx
> -        this.store.zendesk.openSupportTicket()
I may be mistaken but isn't the `openSupportTicket` function only available for zendesk? 
we will still be able to view the beacon as this will be displayed on the store page.

2022-08-24 23:27 UTC, seniorquico approved these changes

2022-08-25 14:25 UTC, merged