[App] Discount labels in store
SaladTechnologies/salad-applications pull request #951
Opened 2022-09-15 22:25 UTC by jpark799

Top Chops:
![image](https://user-images.githubusercontent.com/37646831/190518465-f26f4d69-a086-493b-b628-a4d6eb80dbdb.png)

![image](https://user-images.githubusercontent.com/37646831/190518487-5bc9d6da-b064-4e1e-8157-4d058e7bf97d.png)
Reward Details Page:
![image](https://user-images.githubusercontent.com/37646831/190518516-dfb4ec31-069c-4912-8d98-c06e3d531a1d.png)
Search Results:
![image](https://user-images.githubusercontent.com/37646831/190518528-c949e806-c1cd-4c45-bfc2-b895d5341b33.png)

2022-09-16 20:48 UTC, scottcinatl requested changes

2022-09-16 20:48 UTC, scottcinatl commented on packages/web-app/src/modules/reward-views/components/RewardHeaderBar.tsx
> +    paddingRight: 10,
Is it by design to have more padding to the right of the percentage than to the left? It seems odd that the label doesn't have the content centered in the box.

2022-09-16 20:48 UTC, scottcinatl commented on packages/web-app/src/modules/reward-views/components/RewardHeaderBar.tsx
> +              {lowQuanity && !reward?.originalPrice && (
I could understand on the `RewardItem` shown in the storefront that we would want to optimize space (curious about whether low stock is more important information to the user rather than being explicit with showing how much of a discount the user is getting), but for the header it seems like there is ample space to have both labels showing. Not sure if that is desired?

2022-09-16 20:48 UTC, scottcinatl commented on packages/web-app/src/modules/reward-views/components/RewardHeaderBar.tsx
> +                <span className={classes.priceText}>
nit: nested spans are valid HTML, but this breaks away from the pattern that is used in the other labels where the `div` handles the style of the label and the `span` handles the styles for what is inside the label.

2022-09-16 20:48 UTC, scottcinatl commented on packages/web-app/src/modules/reward-views/components/RewardItem.tsx
> +              <span className={classes.priceText}>
nit: nested spans that break from existing pattern

2022-09-16 20:48 UTC, scottcinatl commented on packages/web-app/src/modules/reward/models/Reward.ts
> +  originalPrice?: number
I see that we had to make this change in two different models, but to me there doesn't seem to be a difference in the `Reward` model and the `RewardResource` model, if they are the same/reference the same thing we should only have one of them.

2022-09-16 20:48 UTC, scottcinatl commented on packages/web-app/src/modules/reward/models/SearchResult.ts
> +    let originalPrice: number | undefined = parseFloat(result['original_price']?.raw)
So the types here are incorrect, because we would be assigning `NaN` to original price in which we are typing as either `number | undefined`. I know typescript doesn't have a type for `NaN` and you are catching that case down below. But I think this could be cleaner if before applying the `parseFloat` method that we check if the value is defined first, if not, set it to `undefined`. If it is, `parseFloat` like there is no tomorrow :)

2022-09-16 20:48 UTC, scottcinatl commented on packages/web-app/src/modules/reward-views/components/RewardItem.tsx
> +            {reward && reward?.originalPrice && !outOfStock && (
Since `reward` is already been checked for we don't have to have utilize optional chaining with `reward?.originalPrice` , it could just be `reward.originalPrice`

2022-09-16 20:48 UTC, scottcinatl commented on packages/web-app/src/modules/storefront-views/components/StorefrontRewardItem.tsx
> +            {rewardData && rewardData?.originalPrice && !outOfStock && (
unnecessary optional chaining

2022-09-19 14:02 UTC, jpark799 commented on packages/web-app/src/modules/reward-views/components/RewardHeaderBar.tsx
> +    paddingRight: 10,
that's how the figma specs were. i think the idea was to have the digits in the center not everything including the `-`.

2022-09-19 15:06 UTC, jpark799 commented on packages/web-app/src/modules/reward-views/components/RewardHeaderBar.tsx
> +              {lowQuanity && !reward?.originalPrice && (
yeah that's a good point. I can double check with Armin

2022-09-19 15:27 UTC, jpark799 commented on packages/web-app/src/modules/reward/models/Reward.ts
> +  originalPrice?: number
it looks like there's a couple of difference between the two like `Reward` having a `videos` and checkoutTerms` field. I agree that these probably couple be consolidated but i think that's outside the scope of this PR.

2022-09-19 16:46 UTC, jpark799 commented on packages/web-app/src/modules/reward-views/components/RewardHeaderBar.tsx
> +              {lowQuanity && !reward?.originalPrice && (
checked with armin and he said it felt like there was too much clutter with two tags. i also agree 
![image](https://user-images.githubusercontent.com/37646831/191069975-6f81eaa9-8b9f-48c3-8ba7-cec20e4d2ed5.png)

2022-09-19 19:37 UTC, merged