[App - Alpha Branch] Add must update notifications banner
SaladTechnologies/salad-applications pull request #960
Opened 2022-11-08 11:20 UTC by Maks19

**Description:**
Add must update notifications banner to legacy app

[image](https://user-images.githubusercontent.com/41080668/200549085-9b47ba24-2b4e-494d-b865-63cc31d24539.png)

**Issues:** https://www.notion.so/saladtech/Create-a-banner-with-text-347b4af2021f491ea656aacbc908ee8d ,
https://www.notion.so/saladtech/Implement-a-banner-in-every-section-that-can-support-showing-it-d866700efe9f46309b598d75ca7ef789

2022-11-08 15:19 UTC, jpark799 approved these changes

2022-11-08 15:19 UTC, jpark799 commented on packages/web-app/src/components/elements/MustUpdateNotificationBanner/MustUpdateNotificationBanner.tsx
> +        {userAgent.indexOf(' electron/') > -1 && (
great job! just pulled this branch down and everything is looking great. i didn't realize we could filter for the electron app this way.

2022-11-08 15:28 UTC, jpark799 requested changes
sorry, after looking more closely at the design docs, it looks like we have a little too much padding on the bottom of the banner. can you please update this to reflect what is in the figma? or if ivan/simina says it's not a big deal, i can just approve. just want to make sure we're sticking as close as we can to the designs product is giving us. thank you!


![image](https://user-images.githubusercontent.com/37646831/200605428-576ee6c3-da1f-44c3-9b7e-c8a681aa59a9.png)

![image](https://user-images.githubusercontent.com/37646831/200605930-f351ffa2-a587-428f-b165-e2bc1e18de96.png)

2022-11-08 15:47 UTC, Maks19 commented on packages/web-app/src/components/elements/MustUpdateNotificationBanner/MustUpdateNotificationBanner.tsx
> +        {userAgent.indexOf(' electron/') > -1 && (
Thank you!

2022-11-08 16:11 UTC, jpark799 approved these changes

2022-11-11 14:41 UTC, rners01 approved these changes

2022-11-14 08:38 UTC, merged