[App] Add low quantity label priority over discount label
SaladTechnologies/salad-applications pull request #962
Opened 2022-11-10 13:10 UTC by rners01

- add low quantity label priority over discount label
- fix spacing

<img width="1138" alt="image" src="https://user-images.githubusercontent.com/115642795/201099708-5897d915-f0af-4a22-bc26-11f7f16672e3.png">

<img width="908" alt="image" src="https://user-images.githubusercontent.com/115642795/201099885-050bb195-e539-4cf7-8e8e-ed5b53a34f13.png">

<img width="1228" alt="image" src="https://user-images.githubusercontent.com/115642795/201100020-1bb54d9b-2153-49db-a2e3-596b9a977efb.png">

<img width="1093" alt="image" src="https://user-images.githubusercontent.com/115642795/201100117-bb8d6396-ea56-4b18-87c0-6c4c31d862f7.png">

2022-11-10 15:31 UTC, jpark799 requested changes

2022-11-10 15:31 UTC, jpark799 commented on packages/web-app/src/modules/reward-views/components/RewardItem.tsx
>                  <span className={classes.originalPrice}>{reward.originalPrice}</span> ${reward.price}
```suggestion
                <span className={classes.originalPrice}>${reward.originalPrice}</span> ${reward.price}
```
it looks like we're missing a dollar sign on the discount price. this should fix it (unless that was intentional). 
![image](https://user-images.githubusercontent.com/37646831/201136416-1e87bb1f-dff1-40fe-a04c-bd39691e52ab.png)

it also looks like the discount tag spans over 2 lines when we have 2 lines of prices. i don't think this is desired behavior. can you please double check with armin/ivan? if they say it's okay, i'll go ahead and approve.

thank you!

2022-11-10 15:35 UTC, jpark799 commented on packages/web-app/src/modules/reward-views/components/RewardItem.tsx
>                  <span className={classes.originalPrice}>{reward.originalPrice}</span> ${reward.price}
it looks like we're also going to need this in the `alpha` branch. shoot me a message if you have any questions and happy to talk through it with you.

2022-11-11 12:34 UTC, rners01 commented on packages/web-app/src/modules/reward-views/components/RewardItem.tsx
>                  <span className={classes.originalPrice}>{reward.originalPrice}</span> ${reward.price}
@jpark799 thanks for that, fixed "dollar sign" and one-line discount label
created separate PR for alpha - https://github.com/SaladTechnologies/salad-applications/pull/963

2022-11-11 12:44 UTC, Maks19 approved these changes

2022-11-11 15:33 UTC, jpark799 approved these changes
looking good!

2022-11-12 11:10 UTC, merged