[App] Add users last seen t&c's version update to login flow
SaladTechnologies/salad-applications pull request #974
Opened 2022-12-19 06:09 UTC by rners01

project - https://www.notion.so/saladtech/Terms-Conditions-Update-Flow-565e181573ff4068bc7aa5881a798534
task - https://www.notion.so/saladtech/App-Add-login-register-update-users-last-seen-terms-e90af1576e874adb828e691200beee6a

2022-12-19 11:13 UTC, Maks19 commented on packages/web-app/src/modules/terms-and-conditions/TermsAndConditionsStore.ts
> +        return
Could we log what went wrong here?
As I understand `submitTermsAndConditions` will be triggered after button click so if `pendingTermsVersion` is false user won't see anything and we won't know what happened

2022-12-20 17:01 UTC, scottcinatl commented on packages/web-app/src/Store.ts
> +        this.termsAndConditions.submitTermsAndConditions(),
What is the expected experience on an error here? It seems that in the `submitTermsAndConditions` call that we are not throwing any error if one occurs. Is the user supposed to be able to continue if they aren't able to accept the new terms and conditions?

2022-12-21 10:46 UTC, rners01 commented on packages/web-app/src/modules/terms-and-conditions/TermsAndConditionsStore.ts
> +        return
no, this is for other purposes(Im reusing this logic for login/register flow, there could be no ```pendingTermsVersion``` so I don't want to send request)
if ```pendingTermsVersion``` is ```null```, then user wont even see this whole block with update T&Cs

2022-12-21 10:48 UTC, rners01 commented on packages/web-app/src/Store.ts
> +        this.termsAndConditions.submitTermsAndConditions(),
good question, with existing logic
if user will not be able to update T&Cs he will just keep seeing notification in the widget to update them and update T&Cs block in the account page in web-app

2022-12-21 10:49 UTC, rners01 commented on packages/web-app/src/Store.ts
> +        this.termsAndConditions.submitTermsAndConditions(),
I'll double check that with Ivan, to be sure that such behaviour satisfies is acceptable

2022-12-21 12:44 UTC, rners01 commented on packages/web-app/src/Store.ts
> +        this.termsAndConditions.submitTermsAndConditions(),
yeah, looks like Ivan will be back after holidays
What do you think then @scottcinatl ?

2022-12-22 09:16 UTC, rners01 commented on packages/web-app/src/Store.ts
> +        this.termsAndConditions.submitTermsAndConditions(),
checked with Ivan, he seems ok with existing solution
<img width="686" alt="image" src="https://user-images.githubusercontent.com/115642795/209100444-b9731bfc-0d90-478e-a835-3d3b62d34e3f.png">

2022-12-22 10:07 UTC, rners01 commented on packages/web-app/src/modules/terms-and-conditions/TermsAndConditionsStore.ts
> +        return
@Maks19 updated the solution to drop additional check

2023-01-06 00:48 UTC, scottcinatl requested changes

2023-01-06 02:45 UTC, rners01 commented on packages/web-app/src/Store.ts
> +      if(profile.pendingTermsVersion) {
its all possible, but I wanted to keep `submitTermsAndConditions` clean and simple, as we'r reusing it in couple places

2023-01-11 21:43 UTC, scottcinatl submitted a review, later dismissed

2023-01-11 21:48 UTC, scottcinatl commented on packages/web-app/src/Store.ts
> +      if(profile.pendingTermsVersion) {
I noticed this wasn't automatically formatted by prettier. There should be a space here, when you save. So make sure we are opening the project in the right folder so we get the correct vscode tooling. For instance, I think this project has to be opened in the `salad-applications`  folder. But when jumping around to each project let's just make sure we are opening it from the correct folder.

2023-01-13 08:43 UTC, rners01 commented on packages/web-app/src/Store.ts
> +      if(profile.pendingTermsVersion) {
Its not working, where do you see such config, I can't find it

2023-01-13 08:51 UTC, rners01 commented on packages/web-app/src/Store.ts
> +      if(profile.pendingTermsVersion) {
but anyway fixed,
we should add some eslint config file for it

2023-01-16 10:46 UTC, merged