Seasons section - removed from account/summary sidebar
SaladTechnologies/salad-applications pull request #976
Opened 2023-01-04 14:37 UTC by vitto-moz

https://www.notion.so/saladtech/Hide-Seasons-section-in-the-user-profile-89816fe52f7a484cab666cb625e461c8

Seasons section - removed from `account/summary` sidebar

2023-01-04 17:08 UTC, scottcinatl requested changes

2023-01-04 17:08 UTC, scottcinatl commented on packages/web-app/src/modules/settings-views/SettingsContainer.ts
> +// import { CurrentSeasonPageContainer } from '../seasons-views'
These should probably just be deleted rather than commented out.

2023-01-04 17:11 UTC, scottcinatl commented on packages/web-app/src/modules/settings-views/SettingsContainer.ts
> +// import { CurrentSeasonPageContainer } from '../seasons-views'
There is also an alpha branch version of this app, I would think the same changes need to be made in that branch. 

Should this change also include an updating of the navigation bar with the removal of the links to seasons as well? So it is removed in one PR rather than two? Or is Ivan fine with this removal not all happening in the same update?

2023-01-05 16:45 UTC, scottcinatl commented
@vitto-moz We have two versions of this app. Sometimes changes need to be to both this branch and the [alpha branch/legacy](https://github.com/SaladTechnologies/salad-applications/tree/alpha). I would check with Ivan to see if this is the case for this change.

2023-01-10 11:16 UTC, vitto-moz commented on packages/web-app/src/modules/settings-views/SettingsContainer.ts
> +// import { CurrentSeasonPageContainer } from '../seasons-views'
> These should probably just be deleted rather than commented out.

@scottcinatl 
Just commented, as we temporary hide this functionality.
We can add some comments, or do you still think we have to completely remove it?

2023-01-10 11:45 UTC, vitto-moz commented on packages/web-app/src/modules/settings-views/SettingsContainer.ts
> +// import { CurrentSeasonPageContainer } from '../seasons-views'
@scottcinatl nevermind about my previous comment 
I've found this comment of @seniorquico, for the related PR 
https://github.com/SaladTechnologies/salad-platform/pull/2507#discussion_r1064888607

2023-01-10 16:59 UTC, scottcinatl approved these changes

2023-01-10 17:00 UTC, scottcinatl commented on packages/web-app/src/modules/settings-views/SettingsContainer.ts
> +// import { CurrentSeasonPageContainer } from '../seasons-views'
I approved. But still had a question about whether this PR should also include the garden component package update which also removes the links stuff from the navigation.

2023-01-11 09:29 UTC, Maks19 approved these changes

2023-01-12 11:54 UTC, merged