Disable and redirect legacy app users alpha
SaladTechnologies/salad-applications pull request #982
Opened 2023-02-22 16:30 UTC by vitto-moz

https://www.notion.so/saladtech/Disable-and-redirect-legacy-app-users-ca96c55783cb4fc7b7b8951bf059e43c?pvs=4
https://www.figma.com/file/IV8bjY0Oe393t8c0EWizk8/Product-Designs?node-id=6212%3A56683&t=aV78t11KKPg5X13B-4

2023-02-23 10:26 UTC, Maks19 commented
I don't see new updates screen. Could you please tell me how I can check it?

<img width="989" alt="image" src="https://user-images.githubusercontent.com/41080668/220881009-8e44c775-1995-4ea8-b8ca-3401cebf345c.png">

2023-02-27 16:04 UTC, Maks19 requested changes

2023-02-27 16:13 UTC, vitto-moz commented on packages/web-app/src/components/UpgradePage.tsx
> +}
it doesn't have any component functionality dependency, so it's fine to declare it once and reuse

2023-02-27 16:18 UTC, vitto-moz commented on packages/web-app/src/indexDeprecated.tsx
> +// Import CSS. Order is important!
this functionality wasn't added by me.. I've just took part needed to render `UpgradePage` 
You can find the previous `index.tsx` content here
`src\indexDeprecated.tsx`

2023-02-27 16:20 UTC, vitto-moz commented on packages/web-app/src/index.tsx
> +  }
> If I go http://localhost:3000/earn/referrals I'll see an empty page
> 
> <img alt="image" width="1829" src="https://user-images.githubusercontent.com/41080668/221601077-61e61258-7952-4ca3-a7fa-0f8dd0ab9e6e.png">

there is not corresponded part in the modern application, that refers to Referrals

2023-02-27 16:23 UTC, vitto-moz commented on packages/web-app/src/index.tsx
> +  }
> http://localhost:3000/store

https://app.salad.io/store  is not a relevant link for the old app

2023-02-27 16:26 UTC, vitto-moz commented on packages/web-app/src/index.tsx
> +  }
> there is not corresponded part in the modern application, that refers to Referrals

there is not corresponded part in the modern application, that refers to Referrals

2023-02-27 16:27 UTC, vitto-moz commented on packages/web-app/src/index.tsx
> +  }
> If I go http://localhost:3000/earn/referrals I'll see an empty page
> 
> <img alt="image" width="1829" src="https://user-images.githubusercontent.com/41080668/221601077-61e61258-7952-4ca3-a7fa-0f8dd0ab9e6e.png">

there is not corresponded part in the modern application, that refers to Referrals

2023-02-27 16:27 UTC, Maks19 commented on packages/web-app/src/index.tsx
> +  }
> [earn/referrals](http://localhost:3000/earn/referrals)

I think we have https://salad.com/account/referrals

2023-02-27 16:29 UTC, Maks19 commented on packages/web-app/src/components/UpgradePage.tsx
> +}
But it uses nowhere else except this component and doesn't have export
Should it be declare inside of the component or if it'll be reusable in separate file?

2023-02-27 16:36 UTC, vitto-moz commented on packages/web-app/src/components/UpgradePage.tsx
> +}
I think there is no sense to recreate the function on every render
should we?

2023-02-27 16:44 UTC, Maks19 commented on packages/web-app/src/components/UpgradePage.tsx
> +}
I don't think that it can be a noticeable performance downgrade of deciding to define a function inside
And `send` function is not a re-usable one to be moved it out of the component if I'm not mistaken

2023-02-27 16:48 UTC, vitto-moz commented on packages/web-app/src/indexDeprecated.tsx
> +// Import CSS. Order is important!
we still need `css` for styling the UpgragePage...if I understood the question correctly ..

if the question is: why we have to keep `indexDeprecated.tsx`, I don't have a strong reason ...
I think we should count that we are going to stop develop `alpha`, that's why we can be less strict here :)

2023-02-27 16:50 UTC, Maks19 commented on packages/web-app/src/indexDeprecated.tsx
> +// Import CSS. Order is important!
I was curious about keeping `indexDeprecated.tsx`
Okay we can keep it for the history :)

2023-02-27 16:51 UTC, vitto-moz commented on packages/web-app/src/components/UpgradePage.tsx
> +}
the same thing when you move out the utils functions out of the component, even they are used only for one component..
Could, you share strong reason to move it in the component body?

2023-02-27 16:56 UTC, Maks19 commented on packages/web-app/src/components/UpgradePage.tsx
> +}
It's used only inside this component and this approach follows the code guide which we're used before
You have `handleDownloadSaladClick` inside but `send` out of the component and both functions respond on `click` events

2023-02-27 17:30 UTC, vitto-moz commented on packages/web-app/src/components/UpgradePage.tsx
> +}
`send` is not a handler for `onClose` & `onMaximize` & `onMinimize`, but the function their handlers use. 
Anyway, I've moved `send` in the component

2023-02-27 17:35 UTC, Maks19 submitted a review, later dismissed

2023-03-01 16:55 UTC, seniorquico commented on packages/web-app/src/index.tsx
> +  const isStoreRedirect = window.location.href.includes('rewards') || window.location.href.includes('search')
Small nit pick... It's _possible_ these string matches could exist anywhere in the URL but _not_ necessarily at the beginning... But this is used by few people, and the risk is low. Up to you if you think this is good enough or if the match should be more technically accurate.

2023-03-09 18:10 UTC, scottcinatl approved these changes

2023-03-09 18:12 UTC, merged