RewardHeaderBar: Target this reward button - added
SaladTechnologies/salad-applications pull request #986
Opened 2023-03-09 10:24 UTC by vitto-moz

https://www.notion.so/saladtech/Add-Add-to-Chopping-List-Button-to-the-Reward-Page-with-request-d10b569b0cce403fa3c46f3a0f48d5fc?pvs=4
https://www.figma.com/file/neYpmmJ5Y0cKjltKeEE3Si/App-Library?node-id=5223-78336&t=vgaAI6nAsua8QSGa-4
<img width="590" alt="image" src="https://user-images.githubusercontent.com/19843391/223995402-c0248486-6b68-4ff7-a327-198d981ff7a1.png">

2023-03-14 19:54 UTC, seniorquico requested changes

2023-03-20 12:14 UTC, vitto-moz commented on packages/web-app/src/modules/reward-views/components/RewardHeaderBar.tsx
> +            <Button className={classes.targetThisRewardButton} onClick={() => {}}>
there was not the functionality to handle the button click at the time the PR was created.
I have to check current progress to refine if we have for now..

2023-03-27 06:50 UTC, rners01 commented on packages/web-app/src/modules/home-views/NavigationBarContainer.tsx
> +import type { TargetRewardInfo } from '@saladtechnologies/garden-components/lib/components/NavigationBar/components/DesktopNavigationBar/TargetRewardStatus'
doesn't index reexport this to the top?
```suggestion
import type { TargetRewardInfo } from '@saladtechnologies/garden-components'
```

2023-03-27 06:50 UTC, rners01 commented on packages/web-app/src/modules/home-views/NavigationBarContainer.tsx
> +    : undefined
Its no big deal, but we defined that like so
<img width="391" alt="image" src="https://user-images.githubusercontent.com/115642795/227858654-3bbea4b4-184f-4b1e-8d5d-c58f832814b5.png">

2023-03-27 06:50 UTC, rners01 commented on packages/web-app/src/modules/home-views/NavigationBarContainer.tsx
> +    targetReward: targetReward,
```suggestion
    targetReward,
```

2023-03-27 06:50 UTC, rners01 commented on packages/web-app/src/modules/reward-views/RewardDetailsContainer.tsx
> -    onRemoveFromCart: store.rewards.removeFromChoppingCart,
why it was removed?

2023-03-27 06:50 UTC, rners01 commented on packages/web-app/src/modules/reward-views/RewardDetailsContainer.tsx
> +  const isTargetReward = store.rewards.selectedReward?.id === reward?.id
```suggestion
  const isRewardSelectedAsTargetReward = store.rewards.selectedReward?.id === reward?.id
```

2023-03-27 06:50 UTC, rners01 commented on packages/web-app/src/modules/reward/RewardStore.tsx
> +  public get selectedReward(): Reward | undefined {
```suggestion
  public get selectedTargetReward(): Reward | undefined {
```

2023-03-27 06:50 UTC, rners01 commented on packages/web-app/src/modules/reward/RewardStore.tsx
> +    if (this.selectedRewardId) {
```suggestion
    if (this.selectedTargetRewardId) {
```

2023-03-27 06:50 UTC, rners01 commented on packages/web-app/src/modules/reward/RewardStore.tsx
> +  setSelectedReward = flow(function* (this: RewardStore, reward: Reward) {
and in other cases
```suggestion
  setTargetSelectedReward = flow(function* (this: RewardStore, reward: Reward) {
```

2023-03-27 18:09 UTC, Maks19 commented
I found a bag with the first reward render
It shows Remove As Target Reward button firstly

https://user-images.githubusercontent.com/41080668/228028280-7485147b-c81c-4e8b-99d5-3c3aa2d676de.mp4

2023-03-28 11:25 UTC, vitto-moz commented on packages/web-app/src/modules/home-views/NavigationBarContainer.tsx
> +import type { TargetRewardInfo } from '@saladtechnologies/garden-components/lib/components/NavigationBar/components/DesktopNavigationBar/TargetRewardStatus'
unfortunately the import you have suggested is not working

2023-03-28 11:26 UTC, vitto-moz commented on packages/web-app/src/modules/home-views/NavigationBarContainer.tsx
> +    : undefined
agree, wonder we don't have this spotted with TS compiler/linter

2023-03-28 12:17 UTC, vitto-moz commented
> I found a bag with the first reward render It shows Remove As Target Reward button firstly

resolved

2023-03-28 12:24 UTC, Maks19 commented on packages/web-app/src/modules/reward-views/components/RewardHeaderBar.tsx
> +  isTargerReward?: boolean
```suggestion
  isTargetReward?: boolean
```

2023-03-28 13:24 UTC, Maks19 submitted a review, later dismissed

2023-03-28 15:31 UTC, Maks19 approved these changes

2023-03-28 15:31 UTC, merged