[App] Fix buy button
SaladTechnologies/salad-applications pull request #994
Opened 2023-03-30 12:02 UTC by Maks19

**Description:** fix buy button

**Issue:** https://www.notion.so/saladtech/BUY-button-inactive-830a8c06c78e4b38923a79f7ae748585

2023-03-30 17:05 UTC, scottcinatl requested changes

2023-03-30 17:05 UTC, scottcinatl commented on packages/web-app/src/modules/reward/RewardStore.tsx
> -    this.isRedeeming = true
I would move this update of the `isRedeeming` state to the start of the `try` block below.

2023-03-30 20:23 UTC, Maks19 commented on packages/web-app/src/modules/salad-pay/SaladPay.tsx
> -    // Check if there is already one and abort previous ones
I left this functionality but split abort and hide logic

2023-03-30 20:25 UTC, Maks19 commented on packages/web-app/src/modules/reward/RewardStore.tsx
> -    if (this.isRedeeming) {
I think `this.processing` is preventing multiple Buy button clicks from occurring. So I'm not sure for what this prop can be using now
https://github.com/SaladTechnologies/salad-applications/blob/master/packages/web-app/src/modules/salad-pay/SaladPayStore.tsx#L42

2023-04-04 15:28 UTC, Maks19 commented on packages/web-app/src/modules/salad-pay/SaladPay.tsx
> -    // Check if there is already one and abort previous ones
Fixed

2023-04-04 15:29 UTC, Maks19 commented on packages/web-app/src/modules/reward/RewardStore.tsx
> -    if (this.isRedeeming) {
Fixed

2023-04-04 15:46 UTC, merged